INSERT INTO "handbook_country" ("id", "name_ru", "name_uz", "name_en", "parent_id", "ins_id", "code", "flag", "is_shengen", "weight", "status", "created_at", "updated_at") VALUES
(279,	'Зона Таиланд',	'Tailand zonasi',	'Thailand zone',	NULL,	NULL,	'',	'',	'0',	0,	1,	NULL,	NULL),
(50,	'Америка',	'Amerika',	'America',	NULL,	NULL,	NULL,	'',	'0',	0,	1,	NULL,	NULL),
(49,	'Азия',	'Osiyo',	'Asia',	NULL,	NULL,	NULL,	'',	'0',	0,	1,	NULL,	NULL),
(53,	'Турзона',	'Turzona',	'Tour zone',	NULL,	NULL,	NULL,	'',	'0',	0,	1,	NULL,	NULL),
(51,	'СНГ',	'MDH',	'CIS',	NULL,	NULL,	NULL,	'',	'0',	0,	1,	NULL,	NULL),
(35,	'Европа',	'Evropa',	'Europe',	NULL,	NULL,	NULL,	'',	'0',	0,	1,	NULL,	NULL),
(148,	'Мальдивы',	'Maldiva',	'Maldives',	279,	NULL,	'MV',	'',	'0',	0,	1,	NULL,	NULL),
(161,	'Норвегия, Шенген',	'Norvegiya, Shengen',	'Norway, Schengen',	140,	NULL,	'NO',	'',	'1',	0,	1,	NULL,	NULL),
(158,	'Узбекистан',	'Uzbekistan',	'Uzbekistan',	64,	NULL,	'UZ',	'',	'0',	0,	1,	NULL,	NULL),
(271,	'Сан-Томе и Принсипи',	'San-Tome va Prinsipi',	'Sao Tome and Principe',	53,	NULL,	'ST',	'',	'0',	0,	1,	NULL,	NULL),
(178,	'Чад',	'Chad',	'Chad',	53,	NULL,	'TD',	'',	'0',	0,	1,	NULL,	NULL),
(212,	'Вануату',	'Vanuatu',	'Vanuatu',	53,	NULL,	'VU',	'',	'0',	0,	1,	NULL,	NULL),
(172,	'Нигерия',	'Nigeriya',	'Nigeria',	53,	NULL,	'NG',	'',	'0',	0,	1,	NULL,	NULL),
(235,	'Гвинея-Бисау',	'Gvineya-Bisau',	'Guinea-Bissau',	53,	NULL,	'GW',	'',	'0',	0,	1,	NULL,	NULL),
(237,	'Сьерра-Леоне',	'Syerra-Leone',	'Sierra Leone',	53,	NULL,	'SL',	'',	'0',	0,	1,	NULL,	NULL),
(239,	'Кабо-Верде',	'Kabo-Verde',	'Cape Verde',	53,	NULL,	'CV',	'',	'0',	0,	1,	NULL,	NULL),
(241,	'Сенегал',	'Senegal',	'Senegal',	53,	NULL,	'SN',	'',	'0',	0,	1,	NULL,	NULL),
(170,	'Кот д''Ивуар',	'Fil suyagi qirg''og''i',	'Cote D''Ivoire',	53,	NULL,	'CI',	'',	'0',	0,	1,	NULL,	NULL),
(238,	'Руанда',	'Ruanda',	'Rwanda',	53,	NULL,	'RW',	'',	'0',	0,	1,	NULL,	NULL),
(249,	'Тонга',	'Tonga',	'Tonga',	53,	NULL,	'TO',	'',	'0',	0,	1,	NULL,	NULL),
(266,	'Свазиленд',	'Svazilend',	'Swaziland',	53,	NULL,	'SZ',	'',	'0',	0,	1,	NULL,	NULL),
(263,	'Того',	'Togo',	'Togo',	53,	NULL,	'TG',	'',	'0',	0,	1,	NULL,	NULL),
(180,	'Французская Полинезия',	'Frantsiya polineziyasi',	'French Polynesia',	53,	NULL,	'PF',	'',	'0',	0,	1,	NULL,	NULL),
(236,	'Экваториальная Гвинея',	'Ekvatorial Gvineya',	'Equatorial Guinea',	53,	NULL,	'GQ',	'',	'0',	0,	1,	NULL,	NULL),
(107,	'Египет',	'Misr',	'Egypt',	53,	NULL,	'EG',	'',	'0',	0,	1,	NULL,	NULL),
(262,	'Лесото',	'Lesoto',	'Lesotho',	53,	NULL,	'LS',	'',	'0',	0,	1,	NULL,	NULL),
(256,	'Тувалу',	'Tuvalu',	'Tuvalu',	53,	NULL,	'TV',	'',	'0',	0,	1,	NULL,	NULL),
(84,	'Вьетнам',	'Vetnam',	'Vietnam',	53,	NULL,	'VN',	'',	'0',	0,	1,	NULL,	NULL),
(99,	'Таиланд',	'Tailand',	'Thailand',	53,	NULL,	'TH',	'',	'0',	0,	1,	NULL,	NULL),
(250,	'Западная Сахара',	'G''arbiy Sahara',	'Western Sahara',	53,	NULL,	'EH',	'',	'0',	0,	1,	NULL,	NULL),
(248,	'Микронезия',	'Mikroneziya',	'Federated States of Micronesia',	53,	NULL,	'FM',	'',	'0',	0,	1,	NULL,	NULL),
(246,	'Бенин',	'Benin',	'Benin',	53,	NULL,	'BJ',	'',	'0',	0,	1,	NULL,	NULL),
(274,	'Палау',	'Palau',	'Palau',	53,	NULL,	'PW',	'',	'0',	0,	1,	NULL,	NULL),
(109,	'Турция',	'Turkiya',	'Turkey',	53,	NULL,	'TR',	'',	'0',	0,	1,	NULL,	NULL),
(242,	'Либерия',	'Liberiya',	'Liberia',	53,	NULL,	'LR',	'',	'0',	0,	1,	NULL,	NULL),
(232,	'Малави',	'Malavi',	'Malawi',	53,	NULL,	'MW',	'',	'0',	0,	1,	NULL,	NULL),
(63,	'ОАЭ (Арабские Эмираты)',	'BAA (Birlashgan Arab Amirligi)',	'UAE (United Arab Emirates)',	53,	NULL,	'AE',	'',	'0',	0,	1,	NULL,	NULL),
(220,	'Замбия',	'Zambiya',	'Zambia',	53,	NULL,	'ZM',	'',	'0',	0,	1,	NULL,	NULL),
(167,	'Самоа',	'Samoa',	'Samoa',	53,	NULL,	'WS',	'',	'0',	0,	1,	NULL,	NULL),
(165,	'Кирибати',	'Kiribati',	'Kiribati',	53,	NULL,	'KI',	'',	'0',	0,	1,	NULL,	NULL),
(208,	'Багамские острова',	'Bagam orollari',	'Bahamas',	53,	NULL,	'BS',	'',	'0',	0,	1,	NULL,	NULL),
(169,	'Ангола',	'Angola',	'Angola',	53,	NULL,	'AO',	'',	'0',	0,	1,	NULL,	NULL),
(204,	'Танзания',	'Tanzaniya',	'Tanzania',	53,	NULL,	'TZ',	'',	'0',	0,	1,	NULL,	NULL),
(171,	'Папуа - Новая Гвинея',	'Papua-Yangi Gvineya',	'Papua New Guinea',	53,	NULL,	'PG',	'',	'0',	0,	1,	NULL,	NULL),
(202,	'Фиджи',	'Fiji',	'Fiji',	53,	NULL,	'FJ',	'',	'0',	0,	1,	NULL,	NULL),
(200,	'Лаос',	'Laos',	'Laos',	53,	NULL,	'LA',	'',	'0',	0,	1,	NULL,	NULL),
(173,	'Гана',	'Gana',	'Ghana',	53,	NULL,	'GH',	'',	'0',	0,	1,	NULL,	NULL),
(177,	'Намибия',	'Namibiya',	'Namibia',	53,	NULL,	'NA',	'',	'0',	0,	1,	NULL,	NULL),
(196,	'Сомали',	'Somali',	'Somalia',	53,	NULL,	'SO',	'',	'0',	0,	1,	NULL,	NULL),
(181,	'Соломоновы острова',	'Sulaymon orollari',	'Solomon Islands',	53,	NULL,	'SB',	'',	'0',	0,	1,	NULL,	NULL),
(187,	'Мадагаскар',	'Madagaskar',	'Madagascar',	53,	NULL,	'MG',	'',	'0',	0,	1,	NULL,	NULL),
(189,	'Джибути',	'Jibuti',	'Djibouti',	53,	NULL,	'DJ',	'',	'0',	0,	1,	NULL,	NULL),
(191,	'Коморские острова',	'Komor',	'Comoros',	53,	NULL,	'KM',	'',	'0',	0,	1,	NULL,	NULL),
(193,	'Габон',	'Gabon',	'Gabon',	53,	NULL,	'GA',	'',	'0',	0,	1,	NULL,	NULL),
(197,	'Мозамбик',	'Mozambik',	'Mozambique',	53,	NULL,	'MZ',	'',	'0',	0,	1,	NULL,	NULL),
(199,	'Антигуа и Барбуда',	'Antigua va Barbuda',	'Antigua And Barbuda',	53,	NULL,	'AG',	'',	'0',	0,	1,	NULL,	NULL),
(203,	'Пуэрто Рико',	'Puerto-Riko',	'Puerto Rico',	53,	NULL,	'PR',	'',	'0',	0,	1,	NULL,	NULL),
(205,	'Буркина-Фасо',	'Burkina-Faso',	'Burkina Faso',	53,	NULL,	'BF',	'',	'0',	0,	1,	NULL,	NULL),
(207,	'Эритрея',	'Eritreya',	'Eritrea',	53,	NULL,	'ER',	'',	'0',	0,	1,	NULL,	NULL),
(209,	'Кения',	'Keniya',	'Kenya',	53,	NULL,	'KE',	'',	'0',	0,	1,	NULL,	NULL),
(231,	'Мали',	'Mali',	'Mali',	53,	NULL,	'ML',	'',	'0',	0,	1,	NULL,	NULL),
(194,	'Ливия',	'Liviya',	'Libya',	53,	NULL,	'LY',	'',	'0',	0,	1,	NULL,	NULL),
(217,	'Уганда',	'Uganda',	'Uganda',	53,	NULL,	'UG',	'',	'0',	0,	1,	NULL,	NULL),
(219,	'Ботсвана',	'Botsvana',	'Botswana',	53,	NULL,	'BW',	'',	'0',	0,	1,	NULL,	NULL),
(192,	'Нигер',	'Niger',	'Niger',	53,	NULL,	'NE',	'',	'0',	0,	1,	NULL,	NULL),
(190,	'Острова Кука',	'Kuk orollari',	'Cook Islands',	53,	NULL,	'CK',	'',	'0',	0,	1,	NULL,	NULL),
(147,	'Малайзия',	'Malayziya',	'Malaysia',	53,	NULL,	'MY',	'',	'0',	0,	1,	NULL,	NULL),
(229,	'Гамбия',	'Gambiya',	'Gambia',	53,	NULL,	'GM',	'',	'0',	0,	1,	NULL,	NULL),
(188,	'Маршалловы острова',	'Marshal orollari',	'Marshall Islands',	53,	NULL,	'MH',	'',	'0',	0,	1,	NULL,	NULL),
(88,	'Сейшелы',	'Seyshel orollari',	'Seychelles islands',	51,	NULL,	'SC',	'',	'0',	0,	1,	NULL,	NULL),
(128,	'Киргизия',	'Qirg''iziston',	'Kyrgyzstan',	51,	NULL,	'KG',	'',	'0',	0,	1,	NULL,	NULL),
(123,	'Казахстан',	'Qozog''iston',	'Kazakhstan',	51,	NULL,	'KZ',	'',	'0',	0,	1,	NULL,	NULL),
(110,	'Индия',	'Hindiston',	'India',	51,	NULL,	'IN',	'',	'0',	0,	1,	NULL,	NULL),
(141,	'Маврикий',	'Mavrikiy',	'Mauritius',	51,	NULL,	'MU',	'',	'0',	0,	1,	NULL,	NULL),
(70,	'Афганистан',	'Afg''oniston',	'Afghanistan',	51,	NULL,	'AF',	'',	'0',	0,	1,	NULL,	NULL),
(126,	'Катар',	'Qatar',	'Qatar',	51,	NULL,	'QA',	'',	'0',	0,	1,	NULL,	NULL),
(131,	'Конго',	'Kongo',	'Congo',	51,	NULL,	'CG',	'',	'0',	0,	1,	NULL,	NULL),
(134,	'Кувейт',	'Quvayt',	'Kuwait',	51,	NULL,	'KW',	'',	'0',	0,	1,	NULL,	NULL),
(64,	'Андорра',	'Andorra',	'Andorra',	51,	NULL,	'AD',	'',	'0',	0,	1,	NULL,	NULL),
(154,	'ЮАР (Южно-Африканская Республика)',	'JAR (Janubiy Afrika Respublikasi)',	'SAR (South African Republic)	',	51,	NULL,	'ZA',	'',	'0',	0,	1,	NULL,	NULL),
(159,	'Центральноафриканская Республика',	'Markaziy Afrika Respublikasi',	'Central African Republic',	51,	NULL,	'CF',	'',	'0',	0,	1,	NULL,	NULL),
(153,	'Эфиопия',	'Efiopiya',	'Ethiopia',	51,	NULL,	'ET',	'',	'0',	0,	1,	NULL,	NULL),
(118,	'Иран',	'Eron',	'Iran',	51,	NULL,	'IR',	'',	'0',	0,	1,	NULL,	NULL),
(75,	'Россия',	'Rossiya',	'Russia',	51,	NULL,	'RU',	'',	'0',	0,	1,	NULL,	NULL),
(85,	'Гвинея',	'Gvineya',	'Guinea',	51,	NULL,	'GN',	'',	'0',	0,	1,	NULL,	NULL),
(98,	'Гонконг',	'Gonkong',	'Hong Kong	',	51,	NULL,	'HK',	'',	'0',	0,	1,	NULL,	NULL),
(57,	'Молдавия, Молдова',	'Moldova',	'Moldavia, Moldova',	51,	NULL,	'MD',	'',	'0',	0,	1,	NULL,	NULL),
(68,	'Армения',	'Armeniya',	'Armenia',	51,	NULL,	'AM',	'',	'0',	0,	1,	NULL,	NULL),
(67,	'Пакистан',	'Pokiston',	'Pakistan',	51,	NULL,	'PK',	'',	'0',	0,	1,	NULL,	NULL),
(92,	'Сирия',	'Suriya',	'Syria',	51,	NULL,	'SY',	'',	'0',	0,	1,	NULL,	NULL),
(114,	'Украина',	'Ukraina',	'Ukraine',	51,	NULL,	'UA',	'',	'0',	0,	1,	NULL,	NULL),
(74,	'Белоруссия',	'Belarusiya',	'Belarus',	51,	NULL,	'BY',	'',	'0',	0,	1,	NULL,	NULL),
(72,	'Бахрейн',	'Bahrayn',	'Bahrain',	51,	NULL,	'BH',	'',	'0',	0,	1,	NULL,	NULL),
(142,	'Шри-Ланка',	'Shri-Lanka',	'Sri-Lanka',	51,	NULL,	'LK',	'',	'0',	0,	1,	NULL,	NULL),
(102,	'Тайвань',	'Tayvan',	'Taiwan',	51,	NULL,	'TW',	'',	'0',	0,	1,	NULL,	NULL),
(230,	'Бурунди',	'Burundi',	'Burundi',	51,	NULL,	'BI',	'',	'0',	0,	1,	NULL,	NULL),
(143,	'Мавритания',	'Mavritaniya',	'Mauritania',	51,	NULL,	NULL,	'',	'0',	0,	1,	NULL,	NULL),
(58,	'Азербайджан',	'Ozarbayjon',	'Azerbaijan',	51,	NULL,	'AZ',	'',	'0',	0,	1,	NULL,	NULL),
(62,	'Алжир',	'Jazoir',	'Algeria',	51,	NULL,	'DZ',	'',	'0',	0,	1,	NULL,	NULL),
(103,	'Тунис',	'Tunis',	'Tunisia',	51,	NULL,	'TN',	'',	'0',	0,	1,	NULL,	NULL),
(101,	'Грузия',	'Gruziya',	'Georgia',	51,	NULL,	'GE',	'',	'0',	0,	1,	NULL,	NULL),
(97,	'Таджикистан',	'Todjikiston',	'Tajikistan',	51,	NULL,	'TJ',	'',	'0',	0,	1,	NULL,	NULL),
(65,	'Оман',	'Ummon',	'Oman',	51,	NULL,	'OM',	'',	'0',	0,	1,	NULL,	NULL),
(213,	'Монголия',	'Mo''g''uliston',	'Mongolia',	51,	NULL,	'MN',	'',	'0',	0,	1,	NULL,	NULL),
(86,	'Саудовская Аравия',	'Saudiya Arabistoni',	'Saudi Arabia',	51,	NULL,	'SA',	'',	'0',	0,	1,	NULL,	NULL),
(105,	'Туркменистан',	'Turkmaniston',	'Turkmenistan',	51,	NULL,	'TM',	'',	'0',	0,	1,	NULL,	NULL),
(111,	'Индонезия',	'Indoneziya',	'Indonesia',	51,	NULL,	'ID',	'',	'0',	0,	1,	NULL,	NULL),
(112,	'Иордания ',	'Iyordaniya',	'Jordan',	51,	NULL,	'JO',	'',	'0',	0,	1,	NULL,	NULL),
(146,	'Македония',	'Makedoniya',	'Macedonia',	51,	NULL,	'MK',	'',	'0',	0,	1,	NULL,	NULL),
(150,	'Марокко',	'Marokko',	'Morocco',	51,	NULL,	'MA',	'',	'0',	0,	1,	NULL,	NULL),
(145,	'Макао',	'Makao',	'Macau',	51,	NULL,	'MO',	'',	'0',	0,	1,	NULL,	NULL),
(115,	'Филиппины',	'Filippin',	'Philippines',	51,	NULL,	'PH',	'',	'0',	0,	1,	NULL,	NULL),
(129,	'Китай',	'Xitoy',	'China',	51,	NULL,	'CN',	'',	'0',	0,	1,	NULL,	NULL),
(228,	'Ирак',	'Iroq',	'Iraq',	51,	NULL,	'IQ',	'',	'0',	0,	1,	NULL,	NULL),
(124,	'Камбоджа',	'Kambodjiya',	'Cambodia',	51,	NULL,	'KH',	'',	'0',	0,	1,	NULL,	NULL),
(261,	'Американские Виргинские острова',	'AQSh Virjiniya orollari',	'US Virgin Islands',	50,	NULL,	'VI',	'',	'0',	0,	1,	NULL,	NULL),
(268,	'Гуам',	'Guam',	'Guam (USA)',	50,	NULL,	'GU',	'',	'0',	0,	1,	NULL,	NULL),
(280,	'Весь мир',	'Butun dunyo',	'Worldwide',	50,	NULL,	'WWD',	'',	'0',	0,	1,	NULL,	NULL),
(273,	'Северные Марианские острова',	'Shimoliy Marian orollari',	'Northern Mariana Islands',	50,	NULL,	'MP',	'',	'0',	0,	1,	NULL,	NULL),
(95,	'США (Соединённые Штаты Америки)',	'AQSH (Amerika Qo''shma shtatlari)',	'USA (United States America)c',	50,	NULL,	'US',	'',	'0',	0,	1,	NULL,	NULL),
(155,	'Южная Корея',	'Janubiy Koreya',	'South Korea',	49,	NULL,	'KR',	'',	'0',	0,	1,	NULL,	NULL),
(77,	'Румыния',	'Ruminiya',	'Romania',	49,	NULL,	'RO',	'',	'0',	0,	1,	NULL,	NULL),
(78,	'Бермудские острова',	'Bermuda orollari',	'Bermuda',	49,	NULL,	'BM',	'',	'0',	0,	1,	NULL,	NULL),
(80,	'Босния и Герцеговина	',	'Bosniya va Gertsogoviniya	',	'Bosnia and Herzegovina	',	49,	NULL,	'BA',	'',	'0',	0,	1,	NULL,	NULL),
(81,	'Бразилия',	'Braziliya',	'Brazil',	49,	NULL,	'BR',	'',	'0',	0,	1,	NULL,	NULL),
(66,	'Аргентина',	'Argentina',	'Argentina',	49,	NULL,	'AR',	'',	'0',	0,	1,	NULL,	NULL),
(60,	'Албания',	'Albaniya',	'Albania',	49,	NULL,	'AL',	'',	'0',	0,	1,	NULL,	NULL),
(79,	'Болгария',	'Bolgariya',	'Bulgaria',	49,	NULL,	'BG',	'',	'0',	0,	1,	NULL,	NULL),
(89,	'Сербия',	'Serbiya',	'Serbia',	49,	NULL,	'RS',	'',	'0',	0,	1,	NULL,	NULL),
(133,	'Куба',	'Kuba',	'Cuba',	49,	NULL,	'CU',	'',	'0',	0,	1,	NULL,	NULL),
(91,	'Сингапур',	'Singapur',	'Singapore',	49,	NULL,	'SG',	'',	'0',	0,	1,	NULL,	NULL),
(69,	'Перу',	'Peru',	'Peru',	49,	NULL,	'PE',	'',	'0',	0,	1,	NULL,	NULL),
(106,	'Доминиканская Республика',	'Dominikan Respublikasi',	'Dominican Republic',	49,	NULL,	'DO',	'',	'0',	0,	1,	NULL,	NULL),
(119,	'Хорватия',	'Xorvatiya',	'Croatia',	49,	NULL,	'HR',	'',	'0',	0,	1,	NULL,	NULL),
(130,	'Черногория',	'Chernogoriya',	'Montenegro',	49,	NULL,	'ME',	'',	'0',	0,	1,	NULL,	NULL),
(127,	'Кипр',	'Kipr',	'Cyprus',	49,	NULL,	'CY',	'',	'0',	0,	1,	NULL,	NULL),
(87,	'Северная Корея',	'Shimoliy Koreya',	'North Korea',	49,	NULL,	'KP',	'',	'0',	0,	1,	NULL,	NULL),
(144,	'Эквадор',	'Ekvador',	'Ecuador',	49,	NULL,	'EC',	'',	'0',	0,	1,	NULL,	NULL),
(163,	'Судан',	'Sudan',	'Sudan',	49,	NULL,	'SD',	'',	'0',	0,	1,	NULL,	NULL),
(183,	'Парагвай',	'Paragvay',	'Paraguay',	49,	NULL,	'PY',	'',	'0',	0,	1,	NULL,	NULL),
(185,	'Гайана',	'Gayana',	'Guyana',	49,	NULL,	'GY',	'',	'0',	0,	1,	NULL,	NULL),
(195,	'Мьянма',	'Myanma',	'Myanmar',	49,	NULL,	'MM',	'',	'0',	0,	1,	NULL,	NULL),
(201,	'Боливия',	'Boliviya',	'Bolivia',	49,	NULL,	'BO',	'',	'0',	0,	1,	NULL,	NULL),
(211,	'Аруба',	'Aruba',	'Aruba',	49,	NULL,	'AW',	'',	'0',	0,	1,	NULL,	NULL),
(225,	'Зимбабве',	'Zimbabve',	'Zimbabwe',	49,	NULL,	'ZW',	'',	'0',	0,	1,	NULL,	NULL),
(227,	'Барбадос',	'Barbados',	'Barbados',	49,	NULL,	'BB',	'',	'0',	0,	1,	NULL,	NULL),
(243,	'Бангладеш',	'Bangladesh',	'Bangladesh',	49,	NULL,	'BD',	'',	'0',	0,	1,	NULL,	NULL),
(247,	'Доминика',	'Dominika',	'Dominica',	49,	NULL,	'DM',	'',	'0',	0,	1,	NULL,	NULL),
(253,	'Сальвадор',	'Salvador',	'El Salvador',	49,	NULL,	'SV',	'',	'0',	0,	1,	NULL,	NULL),
(276,	'Сент-Люсия',	'Sent-Lusiya',	'Saint Lucia',	49,	NULL,	'LC',	'',	'0',	0,	1,	NULL,	NULL),
(156,	'Ямайка',	'Yamayka',	'Jamaica',	49,	NULL,	'JM',	'',	'0',	0,	1,	NULL,	NULL),
(164,	'Суринам',	'Surinam',	'Suriname',	49,	NULL,	'SR',	'',	'0',	0,	1,	NULL,	NULL),
(166,	'Венесуэла',	'Venesuela',	'Venezuela',	49,	NULL,	'VE',	'',	'0',	0,	1,	NULL,	NULL),
(168,	'Йемен',	'Yaman',	'Yemen',	49,	NULL,	'YE',	'',	'0',	0,	1,	NULL,	NULL),
(210,	'Уругвай',	'Urugvay',	'Uruguay',	49,	NULL,	'UY',	'',	'0',	0,	1,	NULL,	NULL),
(174,	'Колумбия',	'Kolumbiya',	'Colombia',	49,	NULL,	'CO',	'',	'0',	0,	1,	NULL,	NULL),
(176,	'Панама',	'Panama',	'Panama',	49,	NULL,	'PA',	'',	'0',	0,	1,	NULL,	NULL),
(151,	'Мексика',	'Meksika',	'Mexico',	49,	NULL,	'MX',	'',	'0',	0,	1,	NULL,	NULL),
(198,	'Чили',	'Chili',	'Chile',	49,	NULL,	'CL',	'',	'0',	0,	1,	NULL,	NULL),
(206,	'Румыния',	'Ruminiya',	'Romania',	49,	NULL,	'RO',	'',	'0',	0,	1,	NULL,	NULL),
(222,	'Непал',	'Nepal',	'Nepal',	49,	NULL,	'NP',	'',	'0',	0,	1,	NULL,	NULL),
(224,	'Ливан',	'Livan',	'Lebanon',	49,	NULL,	'LB',	'',	'0',	0,	1,	NULL,	NULL),
(226,	'Камерун',	'Kamerun',	'Cameroon',	49,	NULL,	'CM',	'',	'0',	0,	1,	NULL,	NULL),
(240,	'Бруней-Даруссалам',	'Bruney Darussalam',	'Brunei Darussalam',	49,	NULL,	'BN',	'',	'0',	0,	1,	NULL,	NULL),
(270,	'Бутан',	'Butan',	'Bhutan',	49,	NULL,	'BT',	'',	'0',	0,	1,	NULL,	NULL),
(175,	'Швейцария, Шенген',	'Shveytsariya, Shengen',	'Switzerland, Schengen',	35,	NULL,	'CH',	'',	'1',	0,	1,	NULL,	NULL),
(275,	'Реюньон',	'Reunion',	'Reunion',	35,	NULL,	'RE',	'',	'0',	0,	1,	NULL,	NULL),
(269,	'Норфолк Айленд',	'Norfolk oroli',	'Norfolk Island',	35,	NULL,	'NF',	'',	'0',	0,	1,	NULL,	NULL),
(216,	'Гаити',	'Gaitida',	'Haiti',	35,	NULL,	'HT',	'',	'0',	0,	1,	NULL,	NULL),
(267,	'Сент-Китс и Невис',	'Sent-Kits va Nevis',	'Saint Kitts and Nevis',	35,	NULL,	'KN',	'',	'0',	0,	1,	NULL,	NULL),
(55,	'Австралия',	'Avstraliya',	'Australia',	35,	NULL,	'AU',	'',	'0',	0,	1,	NULL,	NULL),
(265,	'Фолклендские острова',	'Folklend orollari',	'Falkland Islands',	35,	NULL,	'FK',	'',	'0',	0,	1,	NULL,	NULL),
(259,	'Науру',	'Nauru',	'Nauru',	35,	NULL,	'NR',	'',	'0',	0,	1,	NULL,	NULL),
(152,	'Эстония, Шенген',	'Estoniya, Shengen',	'Estonia, Schengen',	35,	NULL,	'EE',	'',	'1',	0,	1,	NULL,	NULL),
(257,	'Гибралтар',	'Gibraltar',	'Gibraltar',	35,	NULL,	'GI',	'',	'0',	0,	1,	NULL,	NULL),
(59,	'Монако',	'Monako',	'Monaco',	35,	NULL,	'MC',	'',	'0',	0,	1,	NULL,	NULL),
(255,	'Американское Самоа',	'Amerika samoasi',	'American Samoa',	35,	NULL,	'AS',	'',	'0',	0,	1,	NULL,	NULL),
(251,	'Фарерские острова',	'Farer orollari',	'Faroe Islands',	35,	NULL,	'FO',	'',	'0',	0,	1,	NULL,	NULL),
(182,	'Гренландия',	'Grenlandiya',	'Greenland',	35,	NULL,	'GL',	'',	'0',	0,	1,	NULL,	NULL),
(245,	'Кокосовые острова',	'Kokos orollari',	'Cocos (Keeling) Islands',	35,	NULL,	'CC',	'',	'0',	0,	1,	NULL,	NULL),
(233,	'Новая Каледония',	'Yangi Kaledoniya',	'New Conia',	35,	NULL,	'NC',	'',	'0',	0,	1,	NULL,	NULL),
(223,	'Никарагуа',	'Nikaragua',	'Nicaragua',	35,	NULL,	'NI',	'',	'0',	0,	1,	NULL,	NULL),
(221,	'Белиз',	'Beliz',	'Belize',	35,	NULL,	'BZ',	'',	'0',	0,	1,	NULL,	NULL),
(215,	'Теркс и Кайкос',	'Turk va Kaykos',	'Turks and Caicos Islands',	35,	NULL,	'TC',	'',	'0',	0,	1,	NULL,	NULL),
(179,	'Исландия',	'Islandiya',	'Iceland',	35,	NULL,	'IS',	'',	'0',	0,	1,	NULL,	NULL),
(272,	'Тринидад и Тобаго',	'Trinidad va Tobago',	'Trinidad And Tobago',	35,	NULL,	'TT',	'',	'0',	0,	1,	NULL,	NULL),
(96,	'Голландия, Шенген',	'Gollandiya, Shengen',	'Netherlands, Schengen',	35,	NULL,	'NL',	'',	'1',	0,	1,	NULL,	NULL),
(137,	'Швеция, Шенген',	'Shvetsiya, Shengen',	'Sweden, Schengen',	35,	NULL,	'SE',	'',	'1',	0,	1,	NULL,	NULL),
(140,	'Шенгенская зона',	'Shengen hududi',	'Schengen',	35,	NULL,	NULL,	'',	'1',	0,	1,	NULL,	NULL),
(82,	'Великобритания',	'Buyuk Britaniya',	'United Kingdom of Great Britain',	35,	NULL,	'GB',	'',	'1',	0,	1,	NULL,	NULL),
(139,	'Люксембург, Шенген',	'Lyuksemburg, Shengen',	'Luxembourg, Schengen',	35,	NULL,	'LU',	'',	'1',	0,	1,	NULL,	NULL),
(218,	'Коста-Рика',	'Kosta-Rika',	'Costa Rica',	35,	NULL,	'CR',	'',	'0',	0,	1,	NULL,	NULL),
(125,	'Канада',	'Kanada',	'Canada',	35,	NULL,	'CA',	'',	'1',	0,	1,	NULL,	NULL),
(90,	'Германия, Шенген',	'Germaniya, Shengen',	'Germany, Schengen',	35,	NULL,	'DE',	'',	'1',	0,	1,	NULL,	NULL),
(184,	'Гватемала',	'Gvatemala',	'Guatemala',	35,	NULL,	'GT',	'',	'0',	0,	1,	NULL,	NULL),
(186,	'Гондурас',	'Gonduras',	'Honduras',	35,	NULL,	'HN',	'',	'0',	0,	1,	NULL,	NULL),
(149,	'Мальта, Шенген',	'Malta, Shengen',	'Malta, Schengen',	35,	NULL,	'MT',	'',	'1',	0,	1,	NULL,	NULL),
(138,	'Лихтенштейн, Шенген',	'Lixtenshteyn, Shengen',	'Liechtenstein, Schengen',	35,	NULL,	'',	'',	'1',	0,	1,	NULL,	NULL),
(108,	'Израиль',	'Isroil',	'Israel',	35,	NULL,	'IL',	'',	'1',	0,	1,	NULL,	NULL),
(104,	'Дания, Шенген',	'Daniya, Shengen',	'Denmark, Schengen',	35,	NULL,	'DK',	'',	'1',	0,	1,	NULL,	NULL),
(264,	'Монсеррат',	'Montserrat',	'Montserrat',	35,	NULL,	'MS',	'',	'0',	0,	1,	NULL,	NULL),
(234,	'Нидерландские Антильские острова',	'Gollandiya antil orollari',	'Netherlands Antilles',	35,	NULL,	'AN',	'',	'0',	0,	1,	NULL,	NULL),
(76,	'Бельгия, Шенген',	'Belgiya, Shengen',	'Belgium, Schengen',	35,	NULL,	'BE',	'',	'1',	0,	1,	NULL,	NULL),
(132,	'Чехия, Шенген',	'Chexiya, Shengen',	'Czech Republic, Schengen',	35,	NULL,	'CZ',	'',	'1',	0,	1,	NULL,	NULL),
(244,	'Французская Гвиана',	'Frantsiya gvianasi',	'French Guiana',	35,	NULL,	'GF',	'',	'0',	0,	1,	NULL,	NULL),
(135,	'Латвия, Шенген',	'Latviya, Shengen',	'Latvia, Schengen',	35,	NULL,	'LV',	'',	'1',	0,	1,	NULL,	NULL),
(117,	'Франция, Шенген',	'Frantsiya, Shengen',	'France, Schengen',	35,	NULL,	'FR',	'',	'1',	0,	1,	NULL,	NULL),
(252,	'Мартиника',	'Martinika',	'Martinique',	35,	NULL,	'MQ',	'',	'0',	0,	1,	NULL,	NULL),
(121,	'Испания, Шенген',	'Ispaniya, Shengen',	'Spain, Schengen',	35,	NULL,	'ES',	'',	'1',	0,	1,	NULL,	NULL),
(254,	'Сен-Пьер и Микелон',	'Sent-Per va Mikelon',	'St. Pierre and Miquelon',	35,	NULL,	'PM',	'',	'0',	0,	1,	NULL,	NULL),
(122,	'Италия, Шенген',	'Italiya, Shengen',	'Italy, Schengen',	35,	NULL,	'IT',	'',	'1',	0,	1,	NULL,	NULL),
(136,	'Литва, Шенген',	'Litva, Shengen',	'Lithuania, Schengen',	35,	NULL,	'LT',	'',	'1',	0,	1,	NULL,	NULL),
(71,	'Польша, Шенген',	'Polsha, Shengen',	'Poland, Schengen',	35,	NULL,	'PL',	'',	'1',	0,	1,	NULL,	NULL),
(258,	'Гренада',	'Grenada',	'Grenada',	35,	NULL,	'GD',	'',	'0',	0,	1,	NULL,	NULL),
(61,	'Новая Зеландия',	'Yangi Zelandiya',	'New Zealand',	35,	NULL,	'NZ',	'',	'0',	0,	1,	NULL,	NULL),
(157,	'Япония',	'Yaponiya',	'Japan',	35,	NULL,	'JP',	'',	'0',	0,	1,	NULL,	NULL),
(73,	'Португалия, Шенген',	'Portugaliya, Shengen',	'Portugal, Schengen',	35,	NULL,	'PT',	'',	'1',	0,	1,	NULL,	NULL),
(116,	'Финляндия, Шенген',	'Finlandiya, Shengen',	'Finland, Schengen',	35,	NULL,	'FI',	'',	'1',	0,	1,	NULL,	NULL),
(260,	'Ниуэ',	'Niue',	'Niue',	35,	NULL,	'NU',	'',	'0',	0,	1,	NULL,	NULL),
(120,	'Ирландия, Шенген',	'Irlandiya, Shengen',	'Ireland, Schengen',	35,	NULL,	'IE',	'',	'1',	0,	1,	NULL,	NULL),
(100,	'Греция, Шенген',	'Gretsiya, Shengen',	'Greece, Schengen',	35,	NULL,	'GR',	'',	'1',	0,	1,	NULL,	NULL),
(83,	'Венгрия, Шенген',	'Vengriya, Shengen',	'Hungary, Schengen',	35,	NULL,	'HU',	'',	'1',	0,	1,	NULL,	NULL),
(278,	'Остров Рождества',	'Rojdestvo oroli',	'Christmas Island',	35,	NULL,	'CX',	'',	'0',	0,	1,	NULL,	NULL),
(94,	'Словения, Шенген',	'Sloveniya, Shengen',	'Slovenia, Schengen',	35,	NULL,	'SI',	'',	'1',	0,	1,	NULL,	NULL),
(277,	'Острова Уоллис и Футуна',	'Uollis va Futuna orollari',	'Wallis and Futuna Islands',	35,	NULL,	'WF',	'',	'0',	0,	1,	NULL,	NULL),
(214,	'Ангилья',	'Angiliya',	'Anguilla',	35,	NULL,	'AI',	'',	'0',	0,	1,	NULL,	NULL),
(93,	'Словакия, Шенген',	'Slovakiya, Shengen',	'Slovakia, Schengen',	35,	NULL,	'SK',	'',	'1',	0,	1,	NULL,	NULL),
(56,	'Австрия, Шенген',	'Avstriya, Shengen',	'Austria, Schengen',	279,	NULL,	'AT',	'',	'1',	0,	1,	NULL,	NULL);
