INSERT INTO "language_source" ("id", "category", "message") VALUES
(246,	'frontend',	'Пожалуйста попробуйте позже'),
(247,	'frontend',	'Спасибо за ваш отзыв, он появится после проверки модератором.'),
(248,	'frontend',	'Что-то пошло не так. Пожалуйста попробуйте еще раз.'),
(249,	'frontend',	'Ваша почта'),
(250,	'frontend',	'Подписаться'),
(251,	'frontend',	'The requested page does not exist.'),
(252,	'frontend',	'Thank you for contacting us. We will respond to you as soon as possible.'),
(253,	'frontend',	'There was an error sending your message.'),
(254,	'frontend',	'Thank you for Subscribing!'),
(255,	'frontend',	'You have already subscribed'),
(256,	'frontend',	'Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.'),
(257,	'frontend',	'При отправке вашего сообщения произошла ошибка.'),
(259,	'frontend',	'Transaction not found'),
(260,	'frontend',	'Transaction success'),
(262,	'frontend',	'Download policy {policy}'),
(266,	'frontend',	'{label}ни киритинг'),
(275,	'frontend',	'Program'),
(276,	'frontend',	'Address'),
(277,	'frontend',	'Date control'),
(279,	'frontend',	'№'),
(280,	'frontend',	'First name'),
(281,	'frontend',	'Surname'),
(282,	'frontend',	'Patronym'),
(283,	'frontend',	'Date_birth'),
(284,	'frontend',	'Passport'),
(285,	'frontend',	'{label}'),
(288,	'frontend',	'Update'),
(300,	'frontend',	'Search'),
(301,	'frontend',	'Reset'),
(326,	'frontend',	'Выберите способ оплаты'),
(327,	'policy',	'Оплатите через'),
(328,	'frontend',	'____ ____ ____ ____'),
(329,	'frontend',	'Отправить сообщение'),
(330,	'frontend',	'Узнать больше'),
(332,	'frontend',	'Подробнее'),
(335,	'frontend',	'Результатов не найдено.'),
(350,	'frontend',	'Ответить'),
(351,	'frontend',	'На главную'),
(352,	'frontend',	'Опыта на страховом рынке'),
(353,	'frontend',	'НАИВЫСШИЙ уровень платёжеспособности и надежности'),
(355,	'frontend',	'млрд. сум страховых выплат за 2021 год'),
(356,	'frontend',	'Что наши клиенты говорят о нас'),
(357,	'frontend',	'Онлайн страхование'),
(358,	'frontend',	'Купить полис'),
(359,	'frontend',	'Новости'),
(360,	'frontend',	'ПОЛЕЗНЫЕ ССЫЛКИ'),
(361,	'frontend',	'Министерство по развитию информационных технологий'),
(362,	'frontend',	'База данных по законодательству Республики Узбекистан'),
(363,	'frontend',	'Самые популярные страховые продукты'),
(364,	'frontend',	'Посмотреть'),
(365,	'frontend',	'Скачать '),
(366,	'frontend',	'Не нашли информации?'),
(367,	'frontend',	'Задайте вопрос!'),
(368,	'frontend',	'Связаться с нами'),
(369,	'frontend',	'Обратная связь'),
(370,	'frontend',	'Ф.И.О.'),
(371,	'frontend',	'Номер телефона'),
(372,	'frontend',	'Комментарий'),
(373,	'frontend',	'Оставьте заявку, мы обязательно Вам перезвоним.'),
(374,	'frontend',	'Фамилия, Имя и Отчество'),
(375,	'frontend',	'Мобильный телефон'),
(376,	'frontend',	'Ссылка на ваш Телеграм'),
(377,	'frontend',	'Вход'),
(378,	'frontend',	' Восстановить'),
(379,	'frontend',	'Продолжить c :'),
(380,	'frontend',	'Зарегистрироваться'),
(381,	'frontend',	'Пожалуйста, заполните следующие поля, чтобы зарегистрироваться:'),
(382,	'frontend',	'Публичная оферта'),
(383,	'frontend',	'Поля, отмеченные звездочкой (*), обязательны для заполнения.'),
(385,	'frontend',	'Filiallar'),
(386,	'frontend',	'Maxsus imkoniyatlar'),
(387,	'frontend',	'Qulaylik uchun saytning mahsus imkoniyataridan foydalanishingiz mumkin !'),
(388,	'frontend',	'kunduzgi/tungi rejim'),
(389,	'frontend',	'matnni ovozli rejimda o''qish'),
(390,	'frontend',	'matnni katta/kichik rejimga o''girish'),
(391,	'frontend',	'chiqish'),
(392,	'frontend',	'Europrotocol'),
(393,	'frontend',	'Поиск...'),
(394,	'frontend',	'Все права защищены.'),
(395,	'frontend',	'Developed by {companyName}'),
(396,	'frontend',	'Нужна помощь или информация?'),
(397,	'frontend',	'Не стесняйтесь связаться с нами'),
(398,	'frontend',	'Свяжитесь с нами по любому вопросу. Мы поможем ответить на ваше сообщение как можно скорее'),
(399,	'frontend',	'Обслуживание клиентов'),
(400,	'frontend',	'Позвоните нам, чтобы поговорить с членом нашей команды. Мы всегда рады помочь вам.'),
(401,	'frontend',	'Звоните сейчас'),
(402,	'frontend',	'Заказать обратный звонок'),
(403,	'frontend',	'Скрыть окно'),
(404,	'frontend',	'Заполните форму'),
(405,	'frontend',	'Поделитесь мнением о нашей работе, задайте вопрос, закажите звонок'),
(406,	'frontend',	'Укажите имя'),
(407,	'frontend',	'Название компании'),
(408,	'frontend',	'Укажите номер телефона'),
(409,	'frontend',	'E-mail'),
(410,	'frontend',	'Ваше сообщение'),
(411,	'frontend',	'Продолжая, я принимаю'),
(412,	'frontend',	'политику конфиденциальности и'),
(413,	'frontend',	'условия пользования'),
(414,	'frontend',	'Чат Kapita sugurta'),
(415,	'frontend',	'Мы онлайн'),
(416,	'frontend',	'И с радостью готовы вам помочь прямо сейчас'),
(417,	'frontend',	'Muzaffarov'),
(418,	'frontend',	'Petrova'),
(419,	'frontend',	'Sidirova'),
(420,	'frontend',	'Введите сообщение...'),
(421,	'frontend',	'Контакты'),
(422,	'frontend',	'Сбросить пароль'),
(423,	'frontend',	'Выберите новый пароль:'),
(424,	'frontend',	'Сохранить'),
(425,	'frontend',	'Изменить учетную запись'),
(426,	'frontend',	'Выбрать ...'),
(427,	'frontend',	'Обновить'),
(428,	'frontend',	'Запросить сброс пароля'),
(429,	'frontend',	'Пожалуйста, заполните свой адрес электронной почты. Здесь будет отправлена ​​ссылка на сброс пароля.'),
(430,	'frontend',	'Отправить'),
(431,	'frontend',	'Учетная запись'),
(432,	'frontend',	'Пожалуйста, заполните следующие поля для регистрации:'),
(433,	'frontend',	'Публичная оферта интернет-магазина'),
(434,	'frontend',	'<svg class="icon icon--zoom color-white-svg d-flex align-items-center justify-content-center" width="24" height="24">
                            <use xlink:href="#icon--zoom"></use>
                        </svg>'),
(435,	'frontend',	'Результаты поиска для'),
(436,	'frontend',	'ID'),
(437,	'frontend',	'User ID'),
(438,	'frontend',	'Method'),
(439,	'frontend',	'Params'),
(440,	'frontend',	'Request'),
(441,	'frontend',	'Response'),
(442,	'frontend',	'Created At'),
(443,	'frontend',	'{code} - Your verification code for {appName}'),
(444,	'frontend',	'Your order id: {order_id}. Please remember this number!'),
(445,	'frontend',	'User with the same email as in {client} account already exists but isn''t linked to it. Login using email first to link it.'),
(446,	'frontend',	'Unable to save {client} account: {errors}'),
(447,	'frontend',	'Unable to save user: {errors}'),
(448,	'frontend',	'Linked {client} account.'),
(449,	'frontend',	'Unable to link {client} account: {errors}'),
(450,	'frontend',	'Unable to link {client} account. There is another user using it.'),
(451,	'frontend',	'Cache cleared'),
(452,	'frontend',	'Cache modified: '),
(453,	'frontend',	'Cache folders cleared'),
(454,	'frontend',	'Преимущества страхового продукта'),
(455,	'frontend',	'Правила страхования по данному продукту'),
(456,	'frontend',	'Code'),
(457,	'frontend',	'Rate'),
(458,	'frontend',	'Date'),
(459,	'frontend',	'Name'),
(460,	'frontend',	'Car Brand'),
(461,	'frontend',	'Weight'),
(462,	'frontend',	'Status'),
(463,	'frontend',	'Updated At'),
(464,	'frontend',	'Year'),
(465,	'frontend',	'Car Model'),
(466,	'frontend',	'Price'),
(467,	'frontend',	'Update Car Year: {name}'),
(468,	'frontend',	'Car Years'),
(469,	'frontend',	'Delete'),
(470,	'frontend',	'Are you sure you want to delete this item?'),
(471,	'frontend',	'Create Car Year'),
(472,	'frontend',	'Update Car Brand: {name}'),
(473,	'frontend',	'Car Brands'),
(474,	'frontend',	'Create Car Brand'),
(475,	'frontend',	'Save'),
(476,	'frontend',	'Update Car Model: {name}'),
(477,	'frontend',	'Car Models'),
(478,	'frontend',	'Create Car Model'),
(479,	'frontend',	'Select {label}'),
(480,	'frontend',	'Param'),
(481,	'frontend',	'Content'),
(482,	'frontend',	'Model'),
(483,	'frontend',	'Revision ID'),
(484,	'frontend',	'Lang'),
(485,	'frontend',	'Source'),
(486,	'frontend',	'Created By'),
(487,	'frontend',	'Updated By'),
(488,	'frontend',	'Deleted By'),
(489,	'frontend',	'Deleted At'),
(504,	'frontend',	'Update Social Network: {name}'),
(505,	'frontend',	'Social Networks'),
(506,	'frontend',	'Create Social Network'),
(515,	'subscribe',	'Подписаться на рассылку'),
(517,	'policy',	'Хатолик юз берди биз оздан сўнг қайта уриниб кўринг'),
(518,	'policy',	'The requested page does not exist.'),
(520,	'policy',	'Policy not found'),
(521,	'policy',	'Order not found'),
(522,	'policy',	'Policy not payed yet'),
(523,	'policy',	'Home page'),
(525,	'policy',	'Fill in personal information'),
(526,	'policy',	'Calculate Policy'),
(527,	'policy',	'Данные свидетельства о регистрации (техпаспорта) транспортного средства'),
(529,	'policy',	'AAF'),
(532,	'policy',	'Данные собственника транспортного средства'),
(533,	'policy',	'FA'),
(534,	'policy',	'0000001'),
(535,	'policy',	'XXXXXXXXXXXXXX'),
(536,	'policy',	'+998XX-XXX-XX-XX'),
(537,	'policy',	'dd.mm.yyyy'),
(538,	'policy',	'Ҳисоблаш натижалари'),
(539,	'policy',	'Tariff'),
(541,	'policy',	'Search'),
(542,	'policy',	'Reset'),
(545,	'policy',	'Проверка полиса'),
(546,	'policy',	'Policy number'),
(548,	'policy',	'Begin date'),
(549,	'policy',	'End date'),
(550,	'policy',	'Payment'),
(551,	'policy',	'Страховой стоимость'),
(552,	'policy',	'Insurer'),
(553,	'policy',	'Policy info'),
(554,	'policy',	'Phone'),
(555,	'policy',	'Download policy'),
(556,	'policy',	'Download'),
(557,	'policy',	'Проверит'),
(558,	'policy',	'Policy already paid'),
(559,	'policy',	'Payment cancelled'),
(560,	'policy',	'ORDER ID'),
(561,	'policy',	'FIO'),
(562,	'policy',	'PHONE'),
(563,	'policy',	'Program'),
(564,	'policy',	'Program not selected'),
(565,	'policy',	'Полис нархи'),
(566,	'policy',	'сўм'),
(567,	'policy',	'Period'),
(568,	'policy',	'USD'),
(569,	'policy',	'Выберите способ оплаты'),
(570,	'policy',	'Please enter card information'),
(571,	'policy',	'Please enter verification code'),
(572,	'policy',	'__/__'),
(573,	'policy',	''),
(574,	'policy',	'Provided by Payme'),
(575,	'policy',	'Pay with payme'),
(904,	'policy',	'Страховая сумма'),
(916,	'payment',	'Order not found'),
(917,	'payment',	'ID'),
(918,	'payment',	'Order ID'),
(919,	'payment',	'Currency'),
(920,	'payment',	'Total'),
(921,	'payment',	'Amount'),
(922,	'payment',	'Service Transaction ID'),
(923,	'payment',	'Merchant Trans ID'),
(924,	'payment',	'Merchant Prepare ID'),
(925,	'payment',	'Merchant Confirm ID'),
(926,	'payment',	'Service ID'),
(927,	'payment',	'Click Paydoc ID'),
(928,	'payment',	'Sign Time'),
(929,	'payment',	'Sign String'),
(930,	'payment',	'Error'),
(931,	'payment',	'Error Note'),
(932,	'payment',	'User ID'),
(933,	'payment',	'Note'),
(934,	'payment',	'Type'),
(935,	'payment',	'Status'),
(936,	'payment',	'Status Note'),
(937,	'payment',	'Payment methods'),
(938,	'payment',	'Created'),
(939,	'payment',	'Modified'),
(940,	'payment',	'Created At'),
(941,	'payment',	'Updated At'),
(942,	'product',	'Преимущества страхового продукта'),
(943,	'product',	'Правила страхования по данному продукту'),
(944,	'title',	'Все виды страхования KS Insurance'),
(1028,	'fileinput',	'file preview and multiple file upload'),
(1029,	'fileinput',	'multiple file upload'),
(1030,	'fileinput',	'Note:'),
(1031,	'fileinput',	'Your browser does not support {validation}. Try an alternative or more recent browser to access these features.'),
(1102,	'error',	'Хатолик юз берди биз оздан сўнг қайта уриниб кўринг'),
(1103,	'validation',	'Необходимо заполнить'),
(1104,	'validation',	'Дата начала страхования не соответствует требованиям'),
(1105,	'validation',	'Неверный формат телефона'),
(1106,	'validation',	'Это поле обязательно для заполнения.'),
(1107,	'handbook',	'ID'),
(1108,	'handbook',	'Name Ru'),
(1109,	'handbook',	'Name Uz'),
(1110,	'handbook',	'Name En'),
(1111,	'handbook',	'Parent ID'),
(1112,	'handbook',	'Ins ID'),
(1113,	'handbook',	'Code'),
(1114,	'handbook',	'Flag'),
(1115,	'handbook',	'Is Shengen'),
(1116,	'handbook',	'Weight'),
(1117,	'handbook',	'Status'),
(1118,	'handbook',	'Created At'),
(1119,	'handbook',	'Updated At'),
(1120,	'array',	'Inactive'),
(1121,	'array',	'Active'),
(1122,	'array',	'Beta'),
(1123,	'javascript',	'Translation Language: {name}'),
(1124,	'javascript',	'Save'),
(1125,	'javascript',	'Close'),
(1126,	'javascript',	'Are you sure you want to delete these items?'),
(1127,	'javascript',	'Are you sure you want to delete this item?'),
(1129,	'policy',	'Update'),
(1130,	'policy',	'Buy online'),
(1132,	'policy',	'(insurer)'),
(1133,	'policy',	'Insurer information'),
(1134,	'policy',	'{label}ни киритинг'),
(1135,	'policy',	'+99897-000-00-01'),
(1136,	'policy',	'Перейти к просмотру'),
(1137,	'policy',	'Нархни ҳисоблаш'),
(1138,	'policy',	'Выберите'),
(1139,	'policy',	'Parent <span class="index">{0}</span>'),
(1140,	'policy',	'Add parent'),
(1145,	'policy',	'EUR'),
(1146,	'policy',	'Суғурта суммаси'),
(1147,	'policy',	'«Пользовательского соглашения»'),
(1148,	'policy',	'{label} {link}'),
(1149,	'policy',	'Apply'),
(1150,	'policy',	'Parent'),
(1153,	'policy',	'Проверьте данные'),
(1154,	'policy',	'Саёҳат мақсади'),
(1155,	'policy',	'Саёҳат дастури'),
(1157,	'policy',	'№'),
(1158,	'policy',	'First name'),
(1159,	'policy',	'Surname'),
(1160,	'policy',	'Date_birth'),
(1161,	'policy',	'Passport'),
(1162,	'policy',	'Изменить данные'),
(1163,	'policy',	'Перейти к оплате'),
(1164,	'policy',	'01A001AA'),
(1166,	'policy',	'0000000'),
(1167,	'policy',	'Owner Passport/ID sery number'),
(1168,	'policy',	'AF'),
(1170,	'policy',	'Applicant information'),
(1171,	'policy',	'Applicant passport/ID sery number'),
(1172,	'policy',	'Водитель: <span class="index">{0}</span>'),
(1173,	'policy',	'Родственник: <span class="index">{0}</span>'),
(1174,	'policy',	'Delete'),
(1175,	'policy',	'Passport/ID sery number'),
(1176,	'policy',	'Добавить водителя'),
(1177,	'policy',	'Добавить родственник'),
(1178,	'policy',	'Транспортное средство'),
(1179,	'policy',	'Регион регистрации ТС'),
(1180,	'policy',	'Покрытие ущерба, причиненного жизни и здоровью потерпевшего'),
(1181,	'policy',	'%'),
(1182,	'policy',	'Покрытие ущерба, причиненного имуществу потерпевшего'),
(1183,	'policy',	'Ваши данные'),
(1184,	'policy',	'Полное имя'),
(1185,	'policy',	'Паспорт / ID карта'),
(1186,	'policy',	'ПИНФЛ'),
(1187,	'policy',	'Номер телефона'),
(1188,	'policy',	'Владелец транспортного средства'),
(1189,	'policy',	'ИНН'),
(1190,	'policy',	'Информация о транспортном средстве'),
(1191,	'policy',	'Тип, марка и модель ТС'),
(1192,	'policy',	'Год изготовления'),
(1193,	'policy',	'Государственный регистрационный номер'),
(1194,	'policy',	'Номер кузова (шасси) ТС'),
(1195,	'policy',	'Номер двигателя ТС'),
(1196,	'policy',	'Технический паспорт	'),
(1197,	'policy',	'Родственники'),
(1198,	'policy',	'Водители'),
(1199,	'policy',	'Full name'),
(1200,	'policy',	'Passport number'),
(1201,	'policy',	'License number'),
(1202,	'policy',	'Relationship'),
(1203,	'policy',	'Необходимо заполнить'),
(1204,	'policy',	'Yangi polis sotib olindi. Telefon: {phone}. Summasi: {amount_uzs} UZS. To`lov turi: {payment_type}. Polis: {policy}'),
(1205,	'policy',	'❌ Polis to`lovi bekor qilindi. Telefon: {phone}. Summasi: {amount_uzs} UZS. To`lov turi: {payment_type}. Polis: {policy}'),
(1206,	'policy',	'ID'),
(1207,	'policy',	'Policy Osgo'),
(1208,	'policy',	'First Name'),
(1209,	'policy',	'Last Name'),
(1210,	'policy',	'Middle Name'),
(1211,	'policy',	'Birthday'),
(1212,	'policy',	'Passport/ID sery'),
(1213,	'policy',	'Pass/ID Issued By'),
(1214,	'policy',	'Pass/ID Issue Date'),
(1215,	'policy',	'Pinfl'),
(1216,	'policy',	'License series number'),
(1217,	'policy',	'License Number'),
(1218,	'policy',	'License Issue Date'),
(1219,	'policy',	'Email'),
(1220,	'policy',	'Address'),
(1221,	'policy',	'Resident'),
(1222,	'policy',	'Gender'),
(1223,	'policy',	'Created By'),
(1224,	'policy',	'Updated By'),
(1225,	'policy',	'Created At'),
(1226,	'policy',	'Updated At'),
(1227,	'policy',	'Фамилия и имя (Латинскими буквами)'),
(1228,	'policy',	'Отец'),
(1229,	'policy',	'Мать'),
(1230,	'policy',	'Муж'),
(1231,	'policy',	'Жена'),
(1232,	'policy',	'Сын'),
(1233,	'policy',	'Дочь'),
(1234,	'policy',	'Старший брат'),
(1235,	'policy',	'Младший брат'),
(1236,	'policy',	'Старшая сестра'),
(1237,	'policy',	'Младшая сестра'),
(1238,	'policy',	'Гражданин (УзР фуқароси)'),
(1239,	'policy',	'Иностранец (чет эл фуқароси)'),
(1240,	'policy',	'ЛБГ (фуқаролиги йўқ)'),
(1241,	'policy',	'Военный (ҳарбий)'),
(1242,	'policy',	'Иностранный резидент (чет эл резиденти)'),
(1243,	'policy',	'User ID'),
(1244,	'policy',	'Session ID'),
(1245,	'policy',	'Revision ID'),
(1246,	'policy',	'Revision Model'),
(1247,	'policy',	'Total Amount'),
(1248,	'policy',	'Payment Type'),
(1249,	'policy',	'Payment Status'),
(1250,	'policy',	'Status'),
(1251,	'policy',	'Comment'),
(1252,	'policy',	'Start Date'),
(1253,	'policy',	'End Date'),
(1254,	'policy',	'Policy Series'),
(1255,	'policy',	'Policy Number'),
(1256,	'policy',	'Amount Uzs'),
(1257,	'policy',	'Amount Usd'),
(1258,	'policy',	'Регион регистрации транспортного средства'),
(1259,	'policy',	'Region'),
(1260,	'policy',	'Период страхования'),
(1261,	'policy',	'Количество водителей'),
(1262,	'policy',	'Discount ID'),
(1263,	'policy',	'Citizenship'),
(1264,	'policy',	'Owner full name'),
(1265,	'policy',	'Owner First Name'),
(1266,	'policy',	'Owner Last Name'),
(1267,	'policy',	'Owner Middle Name'),
(1268,	'policy',	'Owner Birthday'),
(1269,	'policy',	'Owner Pinfl'),
(1270,	'policy',	'Owner Inn'),
(1271,	'policy',	'Owner Passport/ID sery'),
(1272,	'policy',	'Owner Passport/ID number'),
(1273,	'policy',	'Owner Pass Issued By'),
(1274,	'policy',	'Owner Pass Issue Date'),
(1275,	'policy',	'Мурожаат қилувчи ТВ эгаси'),
(1276,	'policy',	'Район регистрации ТС'),
(1277,	'policy',	'Я также являюсь одним из водителей данного транспортного средства'),
(1278,	'policy',	'Сийлов'),
(1279,	'policy',	'App First Name'),
(1280,	'policy',	'App Last Name'),
(1281,	'policy',	'App Middle Name'),
(1282,	'policy',	'App Birthday'),
(1283,	'policy',	'App Pinfl'),
(1284,	'policy',	'Applicant passport/ID'),
(1285,	'policy',	'App Passport/ID Num'),
(1286,	'policy',	'App Pass Issued By'),
(1287,	'policy',	'App Pass Issue Date'),
(1288,	'policy',	'Owner Phone'),
(1289,	'policy',	'App Email'),
(1290,	'policy',	'App Address'),
(1291,	'policy',	'App Gender'),
(1292,	'policy',	'Legal Type'),
(1293,	'policy',	'Vehicle Gov Number'),
(1294,	'policy',	'Tech Pass Series'),
(1295,	'policy',	'Tech Pass Number'),
(1296,	'policy',	'Tech Pass Issue Date'),
(1297,	'policy',	'Vehicle Model Name'),
(1298,	'policy',	'Vehicle Marka ID'),
(1299,	'policy',	'Vehicle Model ID'),
(1300,	'policy',	'Вид транспортного средства'),
(1301,	'policy',	'Vehicle Issue Year'),
(1302,	'policy',	'Vehicle Body Number'),
(1303,	'policy',	'Vehicle Engine Number'),
(1304,	'policy',	'Source'),
(1305,	'policy',	'Ins Anketa ID'),
(1306,	'policy',	'Ins Policy ID'),
(1307,	'policy',	'Ins Log'),
(1309,	'policy',	'Download policy {policy}'),
(1310,	'policy',	'FIO GEN DIRECTOR'),
(1311,	'policy',	'ПОДТВЕРЖДЁН/ОФОРМЛЕН'),
(1312,	'policy',	'Страхователь подтверждает, что ознакомился и согласен с правилами и условиями публичной оферты добровольного страхования транспортных средств	«{tariff}»'),
(1314,	'policy',	'{label}ни танланг'),
(1315,	'policy',	'Name Ru'),
(1316,	'policy',	'Name Uz'),
(1317,	'policy',	'Name En'),
(1318,	'policy',	'Pokrivaet Covid?'),
(1319,	'policy',	'Parent ID'),
(1320,	'policy',	'Ins ID'),
(1321,	'policy',	'Weight'),
(1322,	'policy',	'Дата начала страхования не соответствует требованиям'),
(1323,	'policy',	'Дата окончания страхования должна быть равна или позже даты начала страхования'),
(1324,	'policy',	'The insurer must be at least 18 years old'),
(1325,	'policy',	'Days'),
(1326,	'policy',	'Purpose ID'),
(1327,	'policy',	'Program ID'),
(1328,	'policy',	'Abroad Group'),
(1329,	'policy',	'Is Family'),
(1330,	'policy',	'App Name'),
(1331,	'policy',	'App Pass Sery'),
(1332,	'policy',	'App Pass Num'),
(1333,	'policy',	'App Phone'),
(1334,	'policy',	'Саёҳатчилар тўлдирилмаган'),
(1335,	'policy',	'Медицинские услуги:'),
(1336,	'policy',	'В том числе COVID-19:'),
(1337,	'policy',	'Evacuation:'),
(1338,	'policy',	'Медико-транспортные услуги:'),
(1339,	'policy',	'Несчастный случай:'),
(1340,	'policy',	'Compensation:'),
(1341,	'policy',	'Итого:'),
(1343,	'policy',	'Country ID'),
(1344,	'policy',	'Member Min'),
(1345,	'policy',	'Member Max'),
(1346,	'policy',	'Rate'),
(1348,	'policy',	'Pass Sery'),
(1349,	'policy',	'Pass Num'),
(1350,	'policy',	'Name'),
(1351,	'policy',	'Age Min'),
(1352,	'policy',	'Age Max'),
(1353,	'policy',	'Day Min'),
(1354,	'policy',	'Day Max'),
(1355,	'policy',	'Value'),
(1356,	'policy',	'Is Fixed'),
(1359,	'frontend',	'Message ID'),
(1360,	'frontend',	'Text'),
(1361,	'frontend',	'Priority'),
(1362,	'frontend',	'Error Code'),
(1363,	'frontend',	'Error Description'),
(1364,	'frontend',	'Код подтверждения отправлено указанный номер '),
(1365,	'frontend',	'Хатолик юз берди биз оздан сўнг қайта уриниб кўринг'),
(1366,	'frontend',	'Phone'),
(1367,	'frontend',	'Policy number'),
(1368,	'frontend',	'Link'),
(1369,	'frontend',	'Lat'),
(1370,	'frontend',	'Lng'),
(1371,	'frontend',	'Call me'),
(1372,	'frontend',	'Video call'),
(1373,	'frontend',	'Car monitoring'),
(1374,	'policy',	'Data not found by pinfl'),
(1375,	'policy',	'Osgo model exception'),
(1376,	'policy',	'Генеральный директор ООО «INSURANCE NAME» FIO.'),
(1377,	'policy',	'unknown'),
(1379,	'policy',	'Texnik pasport seriyasi va raqami'),
(1380,	'policy',	'Водитель'),
(1381,	'policy',	'Родственник'),
(1382,	'policy',	'Добавить водитель'),
(1383,	'policy',	'Пожалуйста попробуйте позже'),
(1384,	'policy',	'Номер карты'),
(1385,	'policy',	'Срок действия карты'),
(1386,	'policy',	'Код для подтверждения'),
(1387,	'policy',	'Thank you for ordering!'),
(1388,	'policy',	'Payment successfully.'),
(1389,	'policy',	'Toshkent shahri'),
(1390,	'policy',	'Toshkent viloyati'),
(1391,	'policy',	'Andijon viloyati'),
(1392,	'policy',	'Buxoro viloyati'),
(1393,	'policy',	'Jizzax viloyati'),
(1394,	'policy',	'Qashqadaryo viloyati'),
(1395,	'policy',	'Qoraqalpog`iston Respublikasi'),
(1396,	'policy',	'Navoiy viloyati'),
(1397,	'policy',	'Namangan viloyati'),
(1398,	'policy',	'Samarqand viloyati'),
(1399,	'policy',	'Sirdaryo viloyati'),
(1400,	'policy',	'Surxondaryo viloyati'),
(1401,	'policy',	'Farg`ona viloyati'),
(1402,	'policy',	'Xorazm viloyati'),
(1404,	'policy',	'Xatolik!!! Polis berilmadi.'),
(1405,	'policy',	'Policy series'),
(1406,	'policy',	'У провайдера данных случилась непредвиденная ошибка'),
(1407,	'policy',	'Данных по предоставленным параметрам не найдено'),
(1408,	'policy',	'Государственный номер автомобиля не соответствует выбранному региону!'),
(1409,	'policy',	'Вид транспортного средства не соответствует выбранному типу!'),
(1410,	'policy',	'Легковые автомобили'),
(1411,	'policy',	'Грузовые автомобили'),
(1412,	'policy',	'Автобусы и микроавтобусы'),
(1413,	'policy',	'Трамваи, мотоциклы и мотороллеры, тракторы, самоходные дорожно-строительные и иные машины'),
(1414,	'policy',	'г.Ташкент и Ташкентская область'),
(1415,	'policy',	'Другие регионы'),
(1416,	'policy',	'Не ограничено'),
(1417,	'policy',	'Ограничено до 5 человек'),
(1418,	'policy',	'1 год'),
(1419,	'policy',	'6 месяцев'),
(1420,	'policy',	'БЕЗ ЛЬГОТ'),
(1421,	'policy',	'ПЕНСИОНЕР'),
(1422,	'policy',	'ИНВАЛИД'),
(1423,	'policy',	'УЧАСТНИК ВОЙНЫ 1941-1945 ЛИБО ПРИРАВНЕННЫМИ К НИМ ЛИЦАМИ'),
(1424,	'policy',	'ВЕТЕРАН ТРУДОВОГО ФРОНТА 1941-1945'),
(1425,	'policy',	'БЫВШИЙ УЗНИК КОНЦЕНТРАЦИОННЫХ ЛАГЕРЕЙ'),
(1426,	'policy',	'ВДОВА/РОДИТЕЛЬ ПОГИБШЕГО ВОЕННОСЛУЖАЩЕГО'),
(1427,	'policy',	'ПОСТРАДАВШИЙ В ЧЕРНОБОЛЬСКОЙ АЭС'),
(1428,	'policy',	'УЧАСТНИКИ АФГАНСКОЙ ВОЙНЫ'),
(1429,	'policy',	'Sizda siylov mavjud, lekin foydalana olmaysiz! Sababi {policy} raqamli polisni {car_number} avtomoshina uchun ishlatgansiz'),
(1430,	'policy',	'DIDOXda Хатолик юз берди биз оздан сўнг қайта уриниб кўринг'),
(1431,	'policy',	'Polis nomer topilmadi.'),
(1432,	'policy',	'Xatolik!!! Polis uuid berilmadi.'),
(1433,	'policy',	'Yangi E-Polis sotib olindi. Telefon: {phone}. Summasi: {amount_uzs} UZS. To`lov turi: {payment_type}. Polis: {policy}'),
(1434,	'policy',	'Ҳайдовчилар тўлдирилмаган'),
(1435,	'policy',	'sendRequestIns Anketa saqlashda xatolik uuid bosh qaytdi'),
(1436,	'policy',	'sendRequestIns Anketa saqlashda xatolik'),
(1438,	'policy',	'Check policy'),
(1439,	'policy',	'Date control'),
(1440,	'policy',	'Patronym'),
(1441,	'payment',	'Payme'),
(1442,	'payment',	'Click'),
(1443,	'payment',	'APELSIN'),
(1444,	'payment',	'OSON'),
(1445,	'payment',	'TEST'),
(1446,	'payment',	'Не оплачено'),
(1447,	'payment',	'Ожидается оплата'),
(1448,	'payment',	'Оплачено'),
(1449,	'payment',	'Платеж отменен'),
(1450,	'payment',	'Платеж отменена после завершения'),
(1451,	'payment',	'PAY_ERROR'),
(1452,	'policy',	'AA'),
(1453,	'frontend',	'Download policy - {policy}'),
(1454,	'policy',	'Download policy - {policy}'),
(1473,	'frontend',	'O''zbekiston Respublikasi, Toshkent sh., 100000, M.Gandi ko''chasi 44-uy'),
(1474,	'frontend',	'При копировании материалов ссылка на сайт обязательна'),
(1475,	'frontend',	'АО "Company name" НЕ ПРИНИМАЛ РЕШЕНИЕ О ВЫКУПЕ СОБСТВЕННЫХ АКЦИЙ.'),
(1477,	'policy',	'Я прочитал и принимаю'),
(1478,	'policy',	'Выплаченная сумма'),
(1479,	'policy',	'Страховой премия'),
(1482,	'policy',	'Abroad Type'),
(1483,	'policy',	'App Surname'),
(1484,	'policy',	'Red passport sery number'),
(1486,	'policy',	'Детали путешествия'),
(1487,	'policy',	'Multi days'),
(1489,	'footer',	'Политика конфиденциальности'),
(1490,	'footer',	'Условия обслуживания'),
(1491,	'policy',	'OSAGO'),
(1518,	'policy',	'Siz haydovchilar soni CHECKLANGAN polis turini tanladingiz. Kamida 1 nafar haydovchi qo`shishingiz shart'),
(1522,	'policy',	'Iltimos mavjud telefon raqamni kiriting, chunki polis sotib olinganligi haqida sms shu raqamga jo`natiladi.'),
(1523,	'policy',	'Polis generatsiya qilishda xatolik ro`y berdi, agar {app_phone} raqamiga sms bormagan bo`lsa, {phone} raqamiga qo`ng`iroq qilib batafsil ma`lumot olishingiz mumkin'),
(1526,	'frontend',	'Hurmatli foydalanuvchi! Sug''urta polisi uchun to''lovni amalga oshirib bo''lganingizdan so''ng, elektron sug''urta polisni yuklab olish uchun shu sahifaga qaytib kelishingiz kerak bo''ladi.'),
(1527,	'frontend',	'To''vni amalga oshirish uchun o''zingizga qulay to''ov tizimi ustiga bosing!'),
(1528,	'frontend',	'Boshqa usulda amalga oshirilgan to''lovlar qabul qilinmaydi!'),
(1638,	'telegram',	'The requested page does not exist.'),
(1639,	'telegram',	'Assalomu alaykum! / Здравствуйте!'),
(1640,	'telegram',	'✅ Malumotlar saqlandi'),
(1641,	'telegram',	'Iltimos o’zingga qulay tilni tanlang. / Пожалуйста, выберите язык.'),
(1642,	'telegram',	'Iltimos kerakli menuni tanlang'),
(1643,	'telegram',	'Iltimos botimizdan foydalanish uchun telefon raqamingizni jo’nating'),
(1644,	'telegram',	'Share my phone number'),
(1645,	'telegram',	'Qaysi product bo`yicha polis rasmiylashtirmoqchisiz?.'),
(1646,	'telegram',	'Avtotransport vositasi davlat raqamini kirting. Masalan: <b>01A001AA</b>'),
(1647,	'telegram',	'Ma''lumotlarni tekshiring va tasdiqlang!'),
(1648,	'telegram',	'✅ Tasdiqlayman'),
(1649,	'telegram',	'❌ O’zgartiraman'),
(1650,	'telegram',	'Avtotransport vositasini ro''yxatdan o''tkazish to''g''risidagi guvohnoma (texnik pasport) seriyasi va raqamini kirting. Masalan: <b>AAF 1234567</b>'),
(1651,	'telegram',	'✅ Xa'),
(1652,	'telegram',	'❌ Ariza beruvchi boshqa shaxs'),
(1653,	'telegram',	'Ariza beruvchining PINFL (JShShIR)ni yoki Passport Seriya raqamini kiriting'),
(1654,	'telegram',	'Masalan: <b>30101800050014</b> yoki <b>AA 1234567</b>'),
(1655,	'telegram',	'Topilmadi!'),
(1656,	'telegram',	'❌ Yo`q'),
(1657,	'telegram',	'ID'),
(1658,	'telegram',	'T ID'),
(1659,	'telegram',	'Is Bot'),
(1660,	'telegram',	'First Name'),
(1661,	'telegram',	'T Username'),
(1662,	'telegram',	'Language Code'),
(1663,	'telegram',	'Callback Data'),
(1664,	'telegram',	'Current product'),
(1665,	'telegram',	'Current step type'),
(1666,	'telegram',	'Current step value'),
(1667,	'telegram',	'Info'),
(1668,	'telegram',	'Created At'),
(1669,	'telegram',	'Updated At'),
(1670,	'telegram',	'Home'),
(1671,	'telegram',	'New policy'),
(1672,	'telegram',	'Settings'),
(1673,	'telegram',	'My policy'),
(1674,	'telegram',	'Bot User ID'),
(1675,	'telegram',	'Data'),
(1676,	'telegram',	'Contractor ID'),
(1677,	'telegram',	'Create Bot User'),
(1678,	'telegram',	'Bot Users'),
(1679,	'telegram',	'Update Bot User: {name}'),
(1680,	'telegram',	'Update'),
(1681,	'telegram',	'Save'),
(1682,	'telegram',	'Search'),
(1683,	'telegram',	'Reset');
