INSERT INTO "language_translate" ("id", "language", "translation") VALUES
(246,	'uz-UZ',	'Kechirasiz. Ma’lumotlarni yetkazib beruvchi tomonida Xatolik yuz berdi. Bir ozdan so‘ng qayta urinib ko‘ring'),
(246,	'ru-RU',	'Произошла ошибка на стороне поставщика данных. Пожалуйста, попробуйте позже'),
(247,	'uz-UZ',	'Fikr-mulohazangiz uchun rahmat, u moderator tomonidan tekshirilgandan so''ng paydo bo''ladi.'),
(248,	'uz-UZ',	'Nimadir noto''g''ri bajarildi. Iltimos, yana bir bor urinib ko''ring.'),
(249,	'uz-UZ',	'Sizning pochtangiz'),
(250,	'uz-UZ',	'Obuna boʻling'),
(251,	'ru-RU',	'Запрашиваемая страница не существует.'),
(251,	'uz-UZ',	'Talab qilingan sahifa mavjud emas.'),
(252,	'uz-UZ',	'Biz bilan bog''langaningiz uchun tashakkur. Sizga imkon qadar tezroq javob beramiz.'),
(252,	'ru-RU',	'Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.'),
(253,	'ru-RU',	'Произошла ошибка в процессе отправки сообщения.'),
(253,	'uz-UZ',	'Xabaringizni yuborishda xatolik yuz berdi.'),
(254,	'uz-UZ',	'Obuna bo''lganingiz uchun tashakkur!'),
(254,	'ru-RU',	'Спасибо что подписались!'),
(255,	'uz-UZ',	'Siz allaqachon obuna bo''lgansiz'),
(255,	'ru-RU',	'Вы уже подписались'),
(256,	'uz-UZ',	'Biz bilan bog''langaningiz uchun tashakkur. Sizga imkon qadar tezroq javob beramiz.'),
(257,	'uz-UZ',	'Xabaringizni yuborishda xatolik yuz berdi.'),
(259,	'uz-UZ',	'Tranzaksiya topilmadi'),
(259,	'ru-RU',	'Транзакция не найдена'),
(260,	'uz-UZ',	'Tranzaksiya muvaffaqiyati'),
(260,	'ru-RU',	'Успех транзакции'),
(262,	'ru-RU',	'Скачать полис- {policy}'),
(262,	'uz-UZ',	'Poliusni yuklab olish - {policy}'),
(266,	'ru-RU',	'{label}введите'),
(266,	'uz-UZ',	'{label}ni kiгiting'),
(275,	'uz-UZ',	'Dastur'),
(275,	'ru-RU',	'Программа'),
(276,	'ru-RU',	'Адрес'),
(276,	'uz-UZ',	'Manzil'),
(277,	'ru-RU',	'Контроль даты'),
(277,	'uz-UZ',	'Sana nazorati'),
(279,	'ru-RU',	'№'),
(280,	'ru-RU',	'Имя'),
(280,	'uz-UZ',	'Ism'),
(281,	'uz-UZ',	'Familiya'),
(281,	'ru-RU',	'Фамилия'),
(282,	'ru-RU',	'Отчество'),
(282,	'uz-UZ',	'Otasining ismi'),
(283,	'ru-RU',	'Дата рождения'),
(283,	'uz-UZ',	'Tug''ilgan sana'),
(284,	'ru-RU',	'Пасспорт'),
(284,	'uz-UZ',	'Pasport'),
(288,	'ru-RU',	'Обновлять'),
(288,	'uz-UZ',	'Yangilash'),
(300,	'uz-UZ',	'Qidirmoq'),
(300,	'ru-RU',	'Поиск'),
(301,	'ru-RU',	'Перезагрузить'),
(301,	'uz-UZ',	'Qayta o''rnatish'),
(326,	'uz-UZ',	'To''lov usulini tanlang'),
(327,	'ru-RU',	'Для оплаты нажмите на удобную платежную систему'),
(327,	'en-US',	'Choose the payment gateway'),
(327,	'uz-UZ',	'To''lash uchun bosing qulay to''lov tizimi ustiga bosing'),
(329,	'uz-UZ',	'Xabar yubormoq'),
(330,	'uz-UZ',	'Qo''shimcha ma''lumot olish uchun'),
(332,	'uz-UZ',	'Batafsil'),
(332,	'en-US',	'More'),
(335,	'uz-UZ',	'Hech qanday natija topilmadi.'),
(350,	'uz-UZ',	'Javob berish'),
(351,	'uz-UZ',	'Asosiyga'),
(352,	'uz-UZ',	'Sug''urta bozorida tajriba'),
(352,	'en-US',	'Experience in the insurance market'),
(353,	'en-US',	'THE HIGHEST level of solvency and reliability'),
(353,	'uz-UZ',	'ENG YUQORI to''lov qobiliyati va ishonchlilik darajasi'),
(355,	'en-US',	'billion soums of insurance payments for 2021'),
(355,	'uz-UZ',	'2021 yil uchun sug''urta to''lovlari milliard so''mni tashkil etdi'),
(356,	'uz-UZ',	'Mijozlarimiz biz haqimizda nima deyishadi'),
(357,	'uz-UZ',	'Onlayn sug''urta'),
(357,	'en-US',	'ONLINE INSURANCE'),
(358,	'en-US',	'Buy policy'),
(358,	'uz-UZ',	'Sotib olish'),
(359,	'en-US',	'NEWS'),
(359,	'uz-UZ',	'Yangiliklar'),
(360,	'uz-UZ',	'FOYDALI HAVOLALAR'),
(360,	'en-US',	'USEFUL LINKS'),
(361,	'uz-UZ',	'Axborotni rivojlantirish vazirligi texnologiyalar'),
(361,	'ru-RU',	'Министерство по развитию информационных технологий'),
(361,	'en-US',	'Ministry for the Development of Information Technologies'),
(362,	'uz-UZ',	'O''zbekiston Respublikasi qonun hujjatlari ma’lumotlar bazasi'),
(362,	'en-US',	'Database on the legislation of the Republic of Uzbekistan'),
(363,	'uz-UZ',	'Eng mashhur sug''urta mahsulotlari'),
(364,	'uz-UZ',	'Ko''rish'),
(365,	'uz-UZ',	'Yuklash'),
(366,	'uz-UZ',	'Ma''lumot topa olmadingizmi?'),
(367,	'uz-UZ',	'Savol bering!'),
(368,	'uz-UZ',	'Biz bilan bog''lanish'),
(369,	'en-US',	'Feedback'),
(369,	'uz-UZ',	'Qayta aloqa'),
(370,	'en-US',	'Full name'),
(370,	'uz-UZ',	'F.I.SH'),
(371,	'uz-UZ',	'Telefon raqami'),
(371,	'en-US',	'Phone number'),
(372,	'uz-UZ',	'Izoh'),
(372,	'en-US',	'Comment'),
(373,	'uz-UZ',	'So''rov qoldiring, biz sizga qo''ng''iroq qilamiz.'),
(374,	'uz-UZ',	'Familiyasi, ismi va otasining ismi'),
(375,	'uz-UZ',	'Uyali telefon'),
(376,	'uz-UZ',	'Telegram-ga havola'),
(377,	'uz-UZ',	'Kirish'),
(378,	'uz-UZ',	'Qayta tiklash'),
(379,	'uz-UZ',	'Davom eting :'),
(380,	'uz-UZ',	'Roʻyxatdan oʻtish'),
(381,	'uz-UZ',	'Roʻyxatdan oʻtish uchun quyidagi maydonlarni toʻldiring:'),
(382,	'uz-UZ',	'Ommaviy taklif'),
(383,	'uz-UZ',	'Yulduzcha (*) bilan belgilangan maydonlar talab qilinadi.'),
(385,	'ru-RU',	'Филиаллы'),
(385,	'en-US',	'Branches'),
(386,	'ru-RU',	'Специальные возможности'),
(386,	'en-US',	'Special Opportunities'),
(387,	'ru-RU',	'Для удобства вы можете воспользоваться специальными возможностями сайта!'),
(388,	'ru-RU',	'дневной/ночной режим'),
(389,	'ru-RU',	'прочитать текст в голосовом режиме'),
(390,	'ru-RU',	'преобразовать текст в верхний/нижний регистр'),
(391,	'ru-RU',	'выход'),
(392,	'ru-RU',	'Европротокол'),
(393,	'en-US',	'Search...'),
(393,	'uz-UZ',	'Qidirish...'),
(394,	'uz-UZ',	'Barcha huquqlar himoyalangan.'),
(394,	'en-US',	'All rigths reserved.'),
(395,	'ru-RU',	'Разработан {companyName}'),
(395,	'uz-UZ',	'{companyName} tomonidan ishlab chiqilgan'),
(396,	'uz-UZ',	'Yordam yoki ma''lumot kerakmi?'),
(397,	'uz-UZ',	'Biz bilan bog''lanishdan tortinmang'),
(398,	'uz-UZ',	'Har qanday savol uchun biz bilan bog''laning. Biz sizga xabaringizga imkon qadar tezroq javob berishga yordam beramiz.'),
(399,	'uz-UZ',	'Mijozlarga hizmat'),
(400,	'uz-UZ',	'Jamoamiz a''zosi bilan gaplashish uchun bizga qo''ng''iroq qiling. Biz har doim sizga yordam berishdan xursandmiz.'),
(401,	'uz-UZ',	'Hozir qo''ng''iroq qiling'),
(402,	'uz-UZ',	'Qayta qo''ng''iroq qilishni talab qiling'),
(403,	'uz-UZ',	'Oynani yashirish'),
(404,	'uz-UZ',	'Shaklni to''ldiring'),
(405,	'uz-UZ',	'Bizning ishimiz haqida fikringizni bildiring, savol bering, qo''ng''iroq qiling'),
(406,	'uz-UZ',	'Ism kiriting'),
(407,	'uz-UZ',	'Shirkat Nomi'),
(408,	'uz-UZ',	'Telefon raqamingizni kiriting'),
(409,	'uz-UZ',	'Elektron pochta'),
(410,	'uz-UZ',	'Sizning xabaringiz'),
(411,	'uz-UZ',	'Davom etaman, men qabul qilaman'),
(412,	'uz-UZ',	'maxfiylik siyosati va'),
(413,	'uz-UZ',	'foydalanish shartlari'),
(414,	'uz-UZ',	'Chat Kapita sugurta'),
(415,	'uz-UZ',	'Biz onlaynmiz'),
(416,	'uz-UZ',	'Va biz hozir sizga yordam berishdan xursandmiz.'),
(420,	'uz-UZ',	'Xabaringizni kiriting...'),
(421,	'uz-UZ',	'Bog''lanish'),
(421,	'ru-RU',	'Связаться с нами'),
(421,	'en-US',	'Contacts'),
(422,	'uz-UZ',	'Parolni qayta o''rnating'),
(423,	'uz-UZ',	'Yangi parolni tanlang:'),
(424,	'uz-UZ',	'Saqlash'),
(425,	'uz-UZ',	'Hisobni o''zgartirish'),
(426,	'uz-UZ',	'Tanlang ...'),
(427,	'uz-UZ',	'Yangilash'),
(428,	'uz-UZ',	'Parolni tiklashni talab qiling'),
(429,	'uz-UZ',	'Iltimos, elektron pochta manzilingizni kiriting. Parolingizni tiklash uchun havola bu erda joylashtiriladi.'),
(430,	'en-US',	'Send'),
(430,	'uz-UZ',	'Yuborish'),
(431,	'uz-UZ',	'Qayd yozuvi'),
(432,	'uz-UZ',	'Roʻyxatdan oʻtish uchun quyidagi maydonlarni toʻldiring:'),
(433,	'uz-UZ',	'Onlayn do''konning ommaviy taklifi'),
(435,	'uz-UZ',	'Uchun qidiruv natijalari'),
(437,	'ru-RU',	'ID пользователя'),
(438,	'ru-RU',	'Метод'),
(439,	'ru-RU',	'Параметры'),
(440,	'ru-RU',	'Запрос'),
(441,	'ru-RU',	'Ответ'),
(442,	'ru-RU',	'Создано на'),
(443,	'ru-RU',	'{code} - Ваш проверочный код для {appName}'),
(444,	'ru-RU',	'Номер вашего заказа {order_id}. Пожалуйста, запомните этот номер!'),
(445,	'ru-RU',	'Пользователь с таким же адресом электронной почты {clien}, что и в аккаунте, уже существует, но не привязан к нему. Сначала войдите в систему, используя электронную почту, чтобы связать ее.'),
(446,	'ru-RU',	'Не удалось сохранить {client} учётную запись: {errors}'),
(447,	'ru-RU',	'Не удалось сохранить пользователя {errors}'),
(448,	'ru-RU',	'Связанный {client} аккаунт.'),
(449,	'ru-RU',	'Не удалось связать {client} учётную запись: {errors}'),
(450,	'ru-RU',	'Не удалось связать {client} учётную запись. Им пользуется другой пользователь.'),
(451,	'ru-RU',	'Кэш очищен'),
(452,	'ru-RU',	'Кэш изменен:'),
(453,	'ru-RU',	'Папки кеша очищены'),
(454,	'uz-UZ',	'Sug''urta mahsulotining afzalliklari'),
(455,	'uz-UZ',	'Ushbu mahsulot uchun sug''urta qoidalari'),
(456,	'uz-UZ',	'Kod'),
(456,	'ru-RU',	'Код'),
(457,	'ru-RU',	'Оценивать'),
(457,	'uz-UZ',	'Darajasi'),
(458,	'ru-RU',	'Дата'),
(458,	'uz-UZ',	'Sana'),
(459,	'uz-UZ',	'Ism'),
(459,	'ru-RU',	'Имя'),
(460,	'ru-RU',	'Марка машины'),
(460,	'uz-UZ',	'Avtomobil markasi'),
(461,	'uz-UZ',	'Og''irligi'),
(461,	'ru-RU',	'Масса'),
(462,	'ru-RU',	'Статус'),
(462,	'uz-UZ',	'Status'),
(463,	'uz-UZ',	'Yangilangan'),
(463,	'ru-RU',	'Обновлено в'),
(464,	'uz-UZ',	'Yil'),
(464,	'ru-RU',	'Год'),
(465,	'ru-RU',	'Модель автомобиля'),
(465,	'uz-UZ',	'Avtomobil modeli'),
(466,	'ru-RU',	'Цена'),
(466,	'uz-UZ',	'Narxi'),
(467,	'ru-RU',	'Обновить год автомобиля: {name}'),
(467,	'uz-UZ',	'Avtomobil yilini yangilash: {name}'),
(468,	'ru-RU',	'Год автомобиля'),
(468,	'uz-UZ',	'Avtomobil yillari'),
(469,	'ru-RU',	'Удалить'),
(469,	'uz-UZ',	'Oʻchirish'),
(470,	'uz-UZ',	'Haqiqatan ham bu elementni oʻchirib tashlamoqchimisiz?'),
(470,	'ru-RU',	'Вы уверены, что хотите удалить этот элемент?'),
(471,	'uz-UZ',	'Avtomobil yilini yarating'),
(471,	'ru-RU',	'Создать год автомобиля'),
(472,	'uz-UZ',	'Avtomobil brendini yangilash: {name}'),
(472,	'ru-RU',	'Обновить марку автомобиля: {name}'),
(473,	'ru-RU',	'Марки автомобилей'),
(473,	'uz-UZ',	'Avtomobil markalari'),
(474,	'uz-UZ',	'Avtomobil brendini yaratish'),
(474,	'ru-RU',	'Создать марку автомобиля'),
(475,	'ru-RU',	'Сохранять'),
(475,	'uz-UZ',	'Saqlash'),
(476,	'ru-RU',	'Обновить модель автомобиля: {name}'),
(476,	'uz-UZ',	'Avtomobil modelini yangilash: {name}'),
(477,	'uz-UZ',	'Avtomobil modellari'),
(477,	'ru-RU',	'Модели автомобилей'),
(478,	'uz-UZ',	'Avtomobil modeli yaratish'),
(478,	'ru-RU',	'Создать модель автомобиля'),
(479,	'uz-UZ',	'Tanlang {label}'),
(479,	'ru-RU',	'Выбирать {label}'),
(480,	'ru-RU',	'Параметры'),
(481,	'uz-UZ',	'Mazmuni'),
(481,	'ru-RU',	'Содержание'),
(482,	'ru-RU',	'Модель'),
(482,	'uz-UZ',	'Model'),
(483,	'ru-RU',	'Идентификатор версии'),
(483,	'uz-UZ',	'Tahrir identifikatori'),
(484,	'ru-RU',	'язык'),
(484,	'uz-UZ',	'Til'),
(485,	'uz-UZ',	'Manba'),
(485,	'ru-RU',	'Источник'),
(486,	'ru-RU',	'Сделано'),
(486,	'uz-UZ',	'Yaratilgan'),
(487,	'uz-UZ',	'Yangilangan'),
(487,	'ru-RU',	'Обновлено'),
(488,	'uz-UZ',	'Oʻchirilgan'),
(488,	'ru-RU',	'Удалено'),
(489,	'ru-RU',	'Удалено в'),
(489,	'uz-UZ',	'Oʻchirilgan'),
(504,	'uz-UZ',	'Ijtimoiy tarmoqni yangilang: {name}'),
(504,	'ru-RU',	'Обновить социальную сеть'),
(505,	'ru-RU',	'Социальные сети'),
(505,	'uz-UZ',	'Ijtimoiy tarmoqlar'),
(506,	'ru-RU',	'Создать социальную сеть'),
(506,	'uz-UZ',	'Ijtimoiy tarmoq yaratish'),
(515,	'uz-UZ',	'Pochta ro''yxatiga obuna bo''ling'),
(517,	'ru-RU',	'Произошла ошибка на стороне поставщика данных. Пожалуйста, попробуйте позже'),
(517,	'uz-UZ',	'Kechirasiz. Ma’lumotlarni yetkazib beruvchi tomonida Xatolik yuz berdi. Bir ozdan so‘ng qayta urinib ko‘ring'),
(518,	'uz-UZ',	'Sahifa mavjud emas.'),
(520,	'uz-UZ',	'Polis topilmadi'),
(521,	'uz-UZ',	'Buyurtma topilmadi'),
(522,	'uz-UZ',	'Polis hali to''lanmagan'),
(523,	'uz-UZ',	'Bosh sahifa'),
(525,	'ru-RU',	'Заполнение персональных данных'),
(525,	'uz-UZ',	'Shaxsiy ma''lumotlarni to''ldiring'),
(526,	'uz-UZ',	'Hisoblash Polisi'),
(527,	'en-US',	'Data of the registration certificate (technical passport) of the vehicle'),
(527,	'uz-UZ',	'Avtotransport vositasini ro''yxatdan o''tkazish to''g''risidagi guvohnoma (texnik pasport) ma''lumotlari'),
(532,	'uz-UZ',	'Avtomobil egasi ma''lumotlari'),
(532,	'en-US',	'Vehicle owner data'),
(537,	'ru-RU',	'дд.мм.гггг'),
(537,	'uz-UZ',	'kk.oo.yyyy'),
(538,	'en-US',	'Calculation results'),
(538,	'uz-UZ',	'Hisoblash natijalari'),
(538,	'ru-RU',	'Результаты расчета'),
(541,	'uz-UZ',	'Qidirmoq'),
(542,	'uz-UZ',	'Qayta o''rnatish'),
(545,	'uz-UZ',	'Polisni tekshirish'),
(545,	'en-US',	'Check policy'),
(546,	'ru-RU',	'Номер полиса'),
(546,	'uz-UZ',	'Polis nomeri'),
(548,	'uz-UZ',	'Boshlanish sanasi'),
(549,	'ru-RU',	'Дата окончания'),
(549,	'uz-UZ',	'Tugash sanasi'),
(550,	'uz-UZ',	'To''lov'),
(551,	'uz-UZ',	'Sug''urta qiymati'),
(552,	'uz-UZ',	'Sug''urtalovchi'),
(553,	'uz-UZ',	'Polis ma''lumotlari'),
(553,	'ru-RU',	'Информация о полисе'),
(554,	'ru-RU',	'Телефон'),
(554,	'uz-UZ',	'Telefon'),
(555,	'uz-UZ',	'Sug''urta polisni yuklab olish'),
(555,	'ru-RU',	'Скачать страховой полис'),
(556,	'ru-RU',	'Скачать'),
(556,	'uz-UZ',	'Yuklash'),
(557,	'en-US',	'Check'),
(557,	'ru-RU',	'Проверить'),
(557,	'uz-UZ',	'Tekshirish'),
(558,	'uz-UZ',	'Polis allaqachon toʻlangan'),
(559,	'uz-UZ',	'Toʻlov bekor qilindi'),
(560,	'uz-UZ',	'Buyurtma IDsi'),
(560,	'ru-RU',	'Номер заказа'),
(561,	'ru-RU',	'Ф.И.О'),
(561,	'uz-UZ',	'F.I.SH'),
(561,	'en-US',	'F.I.O'),
(562,	'uz-UZ',	'Telefon raqam'),
(562,	'ru-RU',	'Телефон'),
(564,	'uz-UZ',	'Dastur tanlanmagan'),
(565,	'en-US',	'Policy price'),
(565,	'ru-RU',	'Стоимость полиса'),
(565,	'uz-UZ',	'Polis narxi'),
(566,	'en-US',	'soums'),
(566,	'uz-UZ',	'so''m'),
(567,	'uz-UZ',	'Davr'),
(567,	'ru-RU',	'Период страхования'),
(569,	'en-US',	'Select a Payment'),
(569,	'uz-UZ',	'To''lov usulini tanlang'),
(570,	'uz-UZ',	'Iltimos, karta ma''lumotlarini kiriting'),
(571,	'uz-UZ',	'Tasdiqlash kodini kiriting'),
(574,	'uz-UZ',	'Payme tomonidan taqdim etilgan'),
(575,	'uz-UZ',	'Payme bilan to''lash'),
(904,	'uz-UZ',	'Sug‘urta summasi'),
(918,	'uz-UZ',	'Buyurtma IDsi'),
(1102,	'uz-UZ',	'Kechirasiz. Ma’lumotlarni yetkazib beruvchi tomonida Xatolik yuz berdi. Bir ozdan so‘ng qayta urinib ko‘ring'),
(1102,	'ru-RU',	'Произошла ошибка на стороне поставщика данных. Пожалуйста, попробуйте позже'),
(1103,	'uz-UZ',	'To''ldirish majburiy'),
(1129,	'uz-UZ',	'Yangilash'),
(1130,	'uz-UZ',	'Onlayn xarid qiling'),
(1132,	'uz-UZ',	'(sug''urtalovchi)'),
(1133,	'en-US',	'Information of insured'),
(1133,	'uz-UZ',	'Sugʻurta qildiruvchi'),
(1133,	'ru-RU',	'Информация о страхователе'),
(1134,	'uz-UZ',	'{label}ni kiriting'),
(1134,	'ru-RU',	'Введите {label}'),
(1134,	'en-US',	'Enter {label}'),
(1136,	'en-US',	'Go to view'),
(1136,	'uz-UZ',	'Saqlash'),
(1138,	'en-US',	'Select'),
(1138,	'uz-UZ',	'Tanlang'),
(1139,	'uz-UZ',	'Ota-ona <span class="index">{0}</span>'),
(1139,	'ru-RU',	'Родитель <span class="index">{0}</span>'),
(1140,	'ru-RU',	'Добавить родителя'),
(1140,	'uz-UZ',	'Ota-ona qoʻshish'),
(1146,	'en-US',	'Sum insured'),
(1146,	'uz-UZ',	'Sugʻurta summasi'),
(1147,	'en-US',	'Public offer'),
(1147,	'ru-RU',	'публичной оферты'),
(1147,	'uz-UZ',	'Ommaviy oferta'),
(1148,	'ru-RU',	'{label} {link}'),
(1148,	'uz-UZ',	'{link} {label}'),
(1149,	'ru-RU',	'подать заявление'),
(1149,	'uz-UZ',	'Saqlash'),
(1150,	'uz-UZ',	'Ota-ona'),
(1150,	'ru-RU',	'Родитель'),
(1153,	'uz-UZ',	'Ma’lumotlarni tekshirish'),
(1153,	'en-US',	'Check the data'),
(1158,	'uz-UZ',	'Ism'),
(1158,	'ru-RU',	'Имя'),
(1159,	'uz-UZ',	'Familiya'),
(1159,	'ru-RU',	'Фамилия'),
(1160,	'uz-UZ',	'Tug’ilgan sana'),
(1160,	'ru-RU',	'Дата рождения'),
(1162,	'en-US',	'Сhange the data'),
(1162,	'uz-UZ',	'Ma''lumotlarni o''zgartirish'),
(1163,	'uz-UZ',	'To''lovga o''tish'),
(1163,	'en-US',	'Go to payment'),
(1167,	'ru-RU',	'Серия и номер ID/Паспорта'),
(1167,	'uz-UZ',	'Egasini pasport sеriyasi va raqami'),
(1170,	'uz-UZ',	'Ariza beruvchining ma''lumotlari'),
(1170,	'ru-RU',	'Заявитель'),
(1171,	'uz-UZ',	'Pasport/ID raqam'),
(1171,	'ru-RU',	'Серия и номер ID/Паспорта'),
(1172,	'uz-UZ',	'Haydovchi: <span class="index">{0}</span>'),
(1172,	'en-US',	'Driver: <span class="index">{0}</span>'),
(1173,	'uz-UZ',	'Qarindosh: <span class="index">{0}</span>'),
(1173,	'en-US',	'Relative: <span class="index">{0}</span>'),
(1174,	'uz-UZ',	'o''chirish'),
(1174,	'ru-RU',	'Удалить'),
(1175,	'uz-UZ',	'Pasport/ID raqami'),
(1175,	'ru-RU',	'Серия и номер ID/Паспорта'),
(1176,	'uz-UZ',	'Haydovchi qoʻshish'),
(1176,	'en-US',	'Add driver'),
(1177,	'uz-UZ',	'Qarindosh qoʻshish'),
(1177,	'en-US',	'Add relative'),
(1178,	'uz-UZ',	'Transport vositasi'),
(1178,	'en-US',	'Vehicle'),
(1179,	'en-US',	'Vehicle registration region'),
(1179,	'uz-UZ',	'Transport vositasining ro''yhatdan o''tgan hudud'),
(1183,	'en-US',	'Your data'),
(1183,	'uz-UZ',	'Ma''lumotlarni tekshiring'),
(1184,	'en-US',	'Full name'),
(1184,	'uz-UZ',	'To''liq F.I.SH'),
(1185,	'uz-UZ',	'Pasport/ ID karta'),
(1185,	'en-US',	'Passport / ID card'),
(1186,	'uz-UZ',	'JSHSHIR'),
(1186,	'en-US',	'PINFL'),
(1187,	'uz-UZ',	'Telefon raqam'),
(1187,	'en-US',	'Phone number'),
(1188,	'uz-UZ',	'Transport vositasining egasi'),
(1188,	'en-US',	'Vehicle owner'),
(1190,	'en-US',	'Vehicle Information'),
(1190,	'uz-UZ',	'Transport vositasi haqida ma''lumot'),
(1191,	'uz-UZ',	'Transport vositasi modеli'),
(1191,	'en-US',	'Type, mark and model of vehicle'),
(1192,	'uz-UZ',	'Ishlab chiqarilgan yili'),
(1192,	'en-US',	'Year of manufacture'),
(1193,	'en-US',	'State registration number'),
(1193,	'uz-UZ',	'Davlat raqami'),
(1194,	'uz-UZ',	'Transport vositasining kuzov (shassi) raqami'),
(1194,	'en-US',	'Body number (chassis) of the vehicle'),
(1195,	'uz-UZ',	'Transport vositasining dvigatel raqami'),
(1195,	'en-US',	'Vehicle engine number'),
(1196,	'uz-UZ',	'Texnik pasport'),
(1196,	'en-US',	'Technical certificate'),
(1197,	'uz-UZ',	'Qarindoshlar'),
(1197,	'en-US',	'Relatives'),
(1198,	'en-US',	'Drivers'),
(1199,	'uz-UZ',	'To''liq F.I.SH'),
(1199,	'ru-RU',	'Полное имя'),
(1200,	'uz-UZ',	'Passport seriya raqami'),
(1200,	'ru-RU',	'Номер паспорта'),
(1201,	'ru-RU',	'Номер В/У'),
(1201,	'uz-UZ',	'Haydovchilik guvohnomasi raqami'),
(1202,	'uz-UZ',	'Qarindoshlik darajasi'),
(1202,	'ru-RU',	'Степень родства'),
(1203,	'uz-UZ',	'To''ldirish majburiy'),
(1208,	'uz-UZ',	'Ism'),
(1208,	'ru-RU',	'Имя'),
(1209,	'uz-UZ',	'Familiya'),
(1209,	'ru-RU',	'Фамилия'),
(1210,	'ru-RU',	'Отчество'),
(1210,	'uz-UZ',	'Otasining ismi'),
(1211,	'uz-UZ',	'Tug‘ilgan sana'),
(1211,	'ru-RU',	'Дата рождения'),
(1215,	'uz-UZ',	'JSHSHIR'),
(1215,	'ru-RU',	'ПИНФЛ'),
(1216,	'uz-UZ',	'Haydovchilik guvohnomasi raqami'),
(1216,	'ru-RU',	'Серия и номер вод. удостоверения'),
(1217,	'uz-UZ',	'Haydovchilik guvohnomasi raqami'),
(1218,	'uz-UZ',	'Haydovchilik guvohnomasining berilgan sanasi'),
(1218,	'ru-RU',	'Дата выдачи вод. удостоверения'),
(1221,	'uz-UZ',	'Resident'),
(1221,	'ru-RU',	'Гражданство'),
(1227,	'uz-UZ',	'Familiyasi Ismi va Otasining ismi (Lotin harfida)'),
(1227,	'en-US',	'Last and first names (in Latin letters)'),
(1228,	'en-US',	'Father'),
(1228,	'uz-UZ',	'Ota'),
(1229,	'en-US',	'Mother'),
(1229,	'uz-UZ',	'Ona'),
(1230,	'uz-UZ',	'Er'),
(1230,	'en-US',	'Husband'),
(1231,	'en-US',	'Wife'),
(1231,	'uz-UZ',	'Hotin'),
(1232,	'en-US',	'Son'),
(1232,	'uz-UZ',	'O''g''il'),
(1233,	'uz-UZ',	'Qiz'),
(1233,	'en-US',	'Daughter'),
(1234,	'uz-UZ',	'Aka'),
(1234,	'en-US',	'Elder brother'),
(1235,	'uz-UZ',	'Uka'),
(1235,	'en-US',	'Junior brother'),
(1236,	'en-US',	'Elder sister'),
(1236,	'uz-UZ',	'Opa'),
(1237,	'uz-UZ',	'Singil'),
(1237,	'en-US',	'Junior sister'),
(1238,	'ru-RU',	'Гражданин УзР'),
(1238,	'uz-UZ',	'Fuqaro (O''zR fuqarosi)'),
(1238,	'en-US',	'Citizen'),
(1239,	'uz-UZ',	'Chet el fuqorosi'),
(1239,	'en-US',	'Foreigner'),
(1239,	'ru-RU',	'Иностранец'),
(1240,	'ru-RU',	'Без гражданства'),
(1240,	'uz-UZ',	'Fuqaroligi yo''q'),
(1240,	'en-US',	'Alien'),
(1241,	'ru-RU',	'Военный'),
(1241,	'uz-UZ',	'Xarbiy'),
(1242,	'en-US',	'Foreign resident'),
(1242,	'uz-UZ',	'Chet el rezidenti'),
(1242,	'ru-RU',	'Иностранный резидент'),
(1252,	'ru-RU',	'Дата начала'),
(1252,	'uz-UZ',	'Boshlanish sanasi'),
(1253,	'ru-RU',	'Дата окончания'),
(1253,	'uz-UZ',	'Tugash sanasi'),
(1254,	'uz-UZ',	'Polis seriasi'),
(1255,	'ru-RU',	'Номер полиса'),
(1258,	'uz-UZ',	'Avtomobilni ro''yxatga olish hududi'),
(1259,	'ru-RU',	'Регион регистрации'),
(1259,	'uz-UZ',	'Mintaqa'),
(1260,	'uz-UZ',	'Sug''urta muddati'),
(1261,	'uz-UZ',	'Haydovchilar soni'),
(1261,	'en-US',	'Number of drivers'),
(1262,	'uz-UZ',	'Chegirma identifikatori'),
(1264,	'uz-UZ',	'Transport vositasi egasi'),
(1264,	'ru-RU',	'Владелец автомобиля'),
(1268,	'ru-RU',	'Дата рождения'),
(1269,	'ru-RU',	'ПИНФЛ владельца ТС'),
(1269,	'uz-UZ',	'JSHSHIR'),
(1270,	'uz-UZ',	'STIR'),
(1270,	'ru-RU',	'ИНН'),
(1275,	'en-US',	'Owner Is Applicant'),
(1275,	'ru-RU',	'Владелец является заявителем'),
(1275,	'uz-UZ',	'Murojaat qiluvchi TV egasi'),
(1276,	'uz-UZ',	'Avtomobilni ro''yxatdan o''tkazish maydoni'),
(1277,	'uz-UZ',	'Transport vositasining egasi ham haydovchi'),
(1277,	'ru-RU',	'Владелец транспортного средства также является водителем'),
(1277,	'en-US',	'The owner of the vehicle is also the driver'),
(1279,	'uz-UZ',	'Ism'),
(1279,	'ru-RU',	'Имя'),
(1280,	'ru-RU',	'Фамилия'),
(1280,	'uz-UZ',	'Familiya'),
(1281,	'ru-RU',	'Отчество'),
(1281,	'uz-UZ',	'Otasining ismi'),
(1282,	'uz-UZ',	'Tug''ilgan sana'),
(1282,	'ru-RU',	'Дата рождения'),
(1288,	'ru-RU',	'Номер телефона'),
(1288,	'uz-UZ',	'Telefon raqam'),
(1290,	'uz-UZ',	'Manzil'),
(1290,	'ru-RU',	'Адрес'),
(1293,	'uz-UZ',	'Davlat raqami'),
(1293,	'ru-RU',	'Гос. номер'),
(1297,	'ru-RU',	'Модель транспортного средства'),
(1297,	'uz-UZ',	'Avtomobil modeli nomi'),
(1298,	'uz-UZ',	'Avtomobil markasi identifikatori'),
(1299,	'uz-UZ',	'Avtomobil modeli ID'),
(1300,	'uz-UZ',	'Avtomobil turi'),
(1300,	'en-US',	'Vehicle type'),
(1301,	'uz-UZ',	'Avtomobil chiqarilgan yil'),
(1301,	'ru-RU',	'Год выпуска'),
(1302,	'uz-UZ',	'Avtomobil tanasi raqami'),
(1311,	'uz-UZ',	'TASDIQLANGAN / BERILGAN'),
(1312,	'uz-UZ',	'Sugʻurtalovchi avtotransport vositalarini ixtiyoriy sugʻurta qilish boʻyicha ommaviy oferta shartlari bilan tanishganligini va ularga roziligini tasdiqlaydi.	«{tariff}»'),
(1319,	'uz-UZ',	'Ota ID'),
(1321,	'uz-UZ',	'Og''irligi'),
(1322,	'uz-UZ',	'Sug''urta boshlanish sanasi talablarga javob bermaydi'),
(1323,	'uz-UZ',	'Sug''urta tugash sanasi sug''urta boshlangan sanaga teng yoki undan kechroq bo''lishi kerak'),
(1324,	'uz-UZ',	'Sug''urtalovchi kamida 18 yoshda bo''lishi kerak'),
(1325,	'ru-RU',	'Дни'),
(1325,	'uz-UZ',	'Kunlar'),
(1326,	'ru-RU',	'Цель поездки'),
(1326,	'uz-UZ',	'Sayohat maqsadini tanlang'),
(1327,	'ru-RU',	'Выберите программу'),
(1327,	'uz-UZ',	'Dasturni tanlang'),
(1328,	'uz-UZ',	'Chet el guruhi'),
(1329,	'uz-UZ',	'Oila hisoblanadi'),
(1330,	'ru-RU',	'Имя'),
(1330,	'uz-UZ',	'Ism'),
(1331,	'uz-UZ',	'App Pass Sery'),
(1332,	'ru-RU',	'Номер  паспорта'),
(1332,	'uz-UZ',	'Pasport/ID raqam'),
(1333,	'ru-RU',	'Номер телефона'),
(1333,	'uz-UZ',	'Telefon raqam'),
(1335,	'uz-UZ',	'Tibbiy xizmatlar:'),
(1336,	'uz-UZ',	'Shu jumladan COVID-19:'),
(1337,	'uz-UZ',	'Qochish:'),
(1338,	'uz-UZ',	'Tibbiy transport xizmatlari:'),
(1339,	'uz-UZ',	'Baxtsiz hodisa:'),
(1340,	'uz-UZ',	'Kompensatsiya:'),
(1341,	'uz-UZ',	'Jami:'),
(1343,	'uz-UZ',	'Mamlakat identifikatori'),
(1346,	'uz-UZ',	'Darajasi'),
(1348,	'uz-UZ',	'Passport Seriasi'),
(1349,	'uz-UZ',	'Passport raqami'),
(1349,	'ru-RU',	'Номер  паспорта'),
(1350,	'uz-UZ',	'Ism'),
(1356,	'uz-UZ',	'Belgilangan'),
(1365,	'ru-RU',	'Произошла ошибка на стороне поставщика данных. Пожалуйста, попробуйте позже'),
(1365,	'uz-UZ',	'Kechirasiz. Ma’lumotlarni yetkazib beruvchi tomonida Xatolik yuz berdi. Bir ozdan so‘ng qayta urinib ko‘ring'),
(1379,	'ru-RU',	'Серия и номер тех. паспорта'),
(1379,	'en-US',	'Tech Pass Series and Number'),
(1380,	'uz-UZ',	'Haydovchi'),
(1380,	'en-US',	'Driver'),
(1381,	'en-US',	'Relative'),
(1381,	'uz-UZ',	'Qarindosh'),
(1382,	'uz-UZ',	'Haydovchi qoʻshish'),
(1382,	'en-US',	'Add driver'),
(1383,	'ru-RU',	'Произошла ошибка на стороне поставщика данных. Пожалуйста, попробуйте позже'),
(1383,	'uz-UZ',	'Kechirasiz. Ma’lumotlarni yetkazib beruvchi tomonida Xatolik yuz berdi. Bir ozdan so‘ng qayta urinib ko‘ring'),
(1405,	'uz-UZ',	'Polis seriasi'),
(1410,	'en-US',	'Passenger cars'),
(1410,	'uz-UZ',	'Yengil avtomobil'),
(1414,	'en-US',	'Tashkent city and Tashkent region'),
(1414,	'uz-UZ',	'Toshkent.sh va Toshkent viloyati'),
(1416,	'uz-UZ',	'Cheklanmagan'),
(1416,	'en-US',	'Not limited'),
(1417,	'en-US',	'Limited to 5 people'),
(1417,	'uz-UZ',	'5 nafar haydovchigacha cheklangan'),
(1418,	'en-US',	'1 year'),
(1418,	'uz-UZ',	'1 Yil'),
(1430,	'ru-RU',	'Произошла ошибка на стороне поставщика данных. Пожалуйста, попробуйте позже'),
(1430,	'uz-UZ',	'Kechirasiz. Ma’lumotlarni yetkazib beruvchi tomonida Xatolik yuz berdi. Bir ozdan so‘ng qayta urinib ko‘ring'),
(1473,	'ru-RU',	'Республика Узбекистан,г. Ташкент, 100000, ул. М. Ганди, 44'),
(1473,	'en-US',	'Republic of Uzbekistan, Tashkent city, 100000, M.Gandhi street 44'),
(1474,	'en-US',	'When copying materials reference to the site is required'),
(1474,	'uz-UZ',	'Materiallardan nusxa olishda saytga havola ko''rsatish talab qilinadi'),
(1477,	'uz-UZ',	'bilan tanishdim va shartlariga roziman'),
(1477,	'ru-RU',	'Ознакомлен(а) и согласен(а) с условиями'),
(1477,	'en-US',	'I have read and agree the'),
(1478,	'uz-UZ',	'To''langan summa'),
(1479,	'uz-UZ',	'Sug‘urta mukofoti'),
(1482,	'ru-RU',	'Тип полиса'),
(1482,	'uz-UZ',	'Polis turi'),
(1483,	'ru-RU',	'Фамилия'),
(1483,	'uz-UZ',	'Familiya'),
(1484,	'uz-UZ',	'Xorijga chiqish pasport seriya/raqami'),
(1484,	'ru-RU',	'Красный паспортный номер серии'),
(1486,	'en-US',	'Travel details'),
(1486,	'uz-UZ',	'Sug''urta polisini hisoblash'),
(1487,	'uz-UZ',	'Qaytish kunlari'),
(1487,	'ru-RU',	'Дни прибытия'),
(1489,	'uz-UZ',	'Maxfiylik siyosati'),
(1490,	'uz-UZ',	'Xizmat ko’rsatish shartlari'),
(1491,	'uz-UZ',	'Majburiy avtosug''urta (OSAGO)'),
(1491,	'ru-RU',	'ОСГОВТС (ОСАГО)'),
(1518,	'ru-RU',	'Вы выбрали тип полиса ограниченное количество водителей. Вы должны добавить хотя бы 1 водителя'),
(1522,	'ru-RU',	'Пожалуйста, введите существующий номер телефона, так как смс о покупке полиса будет отправлен на этот номер.'),
(1523,	'ru-RU',	'Произошла ошибка во время генерации Полиса, если у вас не было смс для { app_phone }, вы можете получить больше информации, позвонив по телефону {phone }'),
(1526,	'ru-RU',	'Дорогой пользователь! После оплаты страхового полиса вам нужно будет вернуться на эту страницу, чтобы скачать электронный страховой полис.'),
(1527,	'ru-RU',	'Нажмите на удобную платежную систему, чтобы произвести оплату!'),
(1528,	'ru-RU',	'Платежи другими способами не принимаются!'),
(1638,	'ru-RU',	'Запрашиваемая страница не существует.'),
(1639,	'ru-RU',	'Assalomu alaykum! / Здравствуйте!'),
(1640,	'ru-RU',	'✅ Данные сохранены'),
(1641,	'ru-RU',	'Iltimos o’zingizga qulay tilni tanlang. / Пожалуйста, выберите язык.'),
(1641,	'uz-UZ',	'Iltimos o’zingizga qulay tilni tanlang. / Пожалуйста, выберите язык.'),
(1642,	'ru-RU',	'Пожалуйста, выберите нужное меню'),
(1643,	'ru-RU',	'Пожалуйста, пришлите свой номер телефона, чтобы использовать нашего бота'),
(1644,	'uz-UZ',	'Telefon raqamni jo''natish'),
(1644,	'ru-RU',	'Отправить контакт'),
(1645,	'ru-RU',	'Какой страховой полис вы хотите оформить?'),
(1645,	'uz-UZ',	'Qaysi produkt bo`yicha polis rasmiylashtirmoqchisiz?.'),
(1646,	'ru-RU',	'Введите регистрационный номер автомобиля. Например: <b>01A001AA</b>'),
(1647,	'ru-RU',	'Проверьте и подтвердите информацию!'),
(1648,	'ru-RU',	'✅ я одобряю'),
(1649,	'ru-RU',	'❌ я изменю это'),
(1650,	'ru-RU',	'Введите серию и номер свидетельства о регистрации транспортного средства (технического паспорта). Например: <b>AAF 1234567</b>'),
(1651,	'ru-RU',	'✅ Да'),
(1652,	'ru-RU',	'❌ Заявитель — другое лицо'),
(1670,	'uz-UZ',	'Asosiy'),
(1670,	'ru-RU',	'Главная'),
(1671,	'ru-RU',	'Купить новый полис'),
(1671,	'uz-UZ',	'Yangi polis rasmiylashtirish');
